2020-07-02T17:46:07.876Z - info:   [05424] *** FOLDER: y:\Test_Projects\Python ***
2020-07-02T17:46:07.878Z - info:   [05424] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-07-02T17:46:07.879Z - debug:  [05424] Looking for an External Context at y:\Test_Projects\Python
2020-07-02T17:46:07.879Z - debug:  [05424] No External Context at y:\Test_Projects\Python
2020-07-02T17:46:07.881Z - debug:  [05424] Looking for TFVC repository at y:\Test_Projects\Python
2020-07-02T17:46:07.882Z - debug:  [05424] TFVC Creating Tfvc object with localPath='undefined'
2020-07-02T17:46:07.883Z - debug:  [05424] Using TFS proxy: 
2020-07-02T17:46:07.883Z - debug:  [05424] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-07-02T17:46:07.884Z - debug:  [05424] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-07-02T17:46:07.886Z - debug:  [05424] TFVC Repository.CheckVersion
2020-07-02T17:46:07.887Z - debug:  [05424] TFVC: tf add -noprompt -?
2020-07-02T17:46:07.927Z - debug:  [05424] TFVC: spawned new process (duration: 38ms)
2020-07-02T17:46:07.934Z - debug:  [05424] TFVC: spawned new process (duration: 6ms)
2020-07-02T17:46:10.155Z - debug:  [05424] TFVC: add exit code: 0 (duration: 2268ms)
2020-07-02T17:46:10.157Z - debug:  [05424] TFVC Minimum required version: 14.102.0
2020-07-02T17:46:10.157Z - debug:  [05424] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-07-02T17:46:10.158Z - debug:  [05424] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-07-02T17:46:10.159Z - debug:  [05424] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-07-02T17:46:10.164Z - debug:  [05424] TFVC: spawned new process (duration: 5ms)
2020-07-02T17:46:11.933Z - debug:  [05424] TFVC: workfold exit code: 100 (duration: 1774ms)
2020-07-02T17:46:11.936Z - debug:  [05424] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-07-02T17:46:11.937Z - error:  [05424] Execution of the TFVC command line failed unexpectedly.
2020-07-02T17:47:07.836Z - debug:  [05424] Reinitializing due to onDidChangeConfiguration
2020-07-02T17:47:07.838Z - debug:  [05424] Polling interval value (minutes): 5
2020-07-02T17:47:07.838Z - debug:  [05424] Polling interval must be greater than 10 minutes.
2020-07-02T17:47:07.845Z - info:   [05424] *** FOLDER: y:\Test_Projects\Python ***
2020-07-02T17:47:07.845Z - info:   [05424] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-07-02T17:47:07.846Z - debug:  [05424] Looking for an External Context at y:\Test_Projects\Python
2020-07-02T17:47:07.846Z - debug:  [05424] No External Context at y:\Test_Projects\Python
2020-07-02T17:47:07.860Z - debug:  [05424] Reinitializing due to onDidChangeConfiguration
2020-07-02T17:47:07.861Z - debug:  [05424] Polling interval value (minutes): 5
2020-07-02T17:47:07.861Z - debug:  [05424] Polling interval must be greater than 10 minutes.
2020-07-02T17:47:07.866Z - info:   [05424] *** FOLDER: y:\Test_Projects\Python ***
2020-07-02T17:47:07.866Z - info:   [05424] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-07-02T17:47:07.867Z - debug:  [05424] Looking for an External Context at y:\Test_Projects\Python
2020-07-02T17:47:07.867Z - debug:  [05424] No External Context at y:\Test_Projects\Python
2020-07-02T17:47:07.872Z - debug:  [05424] Looking for TFVC repository at y:\Test_Projects\Python
2020-07-02T17:47:07.873Z - debug:  [05424] TFVC Creating Tfvc object with localPath='undefined'
2020-07-02T17:47:07.874Z - debug:  [05424] Using TFS proxy: 
2020-07-02T17:47:07.874Z - debug:  [05424] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-07-02T17:47:07.875Z - debug:  [05424] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-07-02T17:47:07.876Z - debug:  [05424] TFVC Repository.CheckVersion
2020-07-02T17:47:07.878Z - debug:  [05424] TFVC: tf add -noprompt -?
2020-07-02T17:47:07.878Z - debug:  [05424] Looking for TFVC repository at y:\Test_Projects\Python
2020-07-02T17:47:07.879Z - debug:  [05424] TFVC Creating Tfvc object with localPath='undefined'
2020-07-02T17:47:07.879Z - debug:  [05424] Using TFS proxy: 
2020-07-02T17:47:07.879Z - debug:  [05424] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-07-02T17:47:07.880Z - debug:  [05424] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-07-02T17:47:07.880Z - debug:  [05424] TFVC Repository.CheckVersion
2020-07-02T17:47:07.880Z - debug:  [05424] TFVC: tf add -noprompt -?
2020-07-02T17:47:07.899Z - debug:  [05424] TFVC: spawned new process (duration: 18ms)
2020-07-02T17:47:07.900Z - debug:  [05424] TFVC: spawned new process (duration: 12ms)
2020-07-02T17:47:07.900Z - error:  [05424] write after end
2020-07-02T17:47:08.178Z - debug:  [05424] TFVC: add exit code: 0 (duration: 300ms)
2020-07-02T17:47:08.180Z - debug:  [05424] TFVC Minimum required version: 14.102.0
2020-07-02T17:47:08.181Z - debug:  [05424] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-07-02T17:47:08.182Z - debug:  [05424] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-07-02T17:47:08.182Z - debug:  [05424] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-07-02T17:47:08.188Z - debug:  [05424] TFVC: spawned new process (duration: 5ms)
2020-07-02T17:47:08.195Z - debug:  [05424] TFVC: spawned new process (duration: 6ms)
2020-07-02T17:47:08.884Z - debug:  [05424] TFVC: workfold exit code: 100 (duration: 702ms)
2020-07-02T17:47:08.888Z - debug:  [05424] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-07-02T17:47:08.888Z - error:  [05424] Execution of the TFVC command line failed unexpectedly.
2020-07-02T17:47:20.469Z - info:   [14984] *** FOLDER: y:\Test_Projects\Python ***
2020-07-02T17:47:20.470Z - info:   [14984] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-07-02T17:47:20.471Z - debug:  [14984] Looking for an External Context at y:\Test_Projects\Python
2020-07-02T17:47:20.471Z - debug:  [14984] No External Context at y:\Test_Projects\Python
2020-07-02T17:47:20.524Z - debug:  [14984] Looking for TFVC repository at y:\Test_Projects\Python
2020-07-02T17:47:20.524Z - debug:  [14984] TFVC Creating Tfvc object with localPath='undefined'
2020-07-02T17:47:20.526Z - debug:  [14984] Using TFS proxy: 
2020-07-02T17:47:20.526Z - debug:  [14984] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-07-02T17:47:20.527Z - debug:  [14984] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-07-02T17:47:20.528Z - debug:  [14984] TFVC Repository.CheckVersion
2020-07-02T17:47:20.530Z - debug:  [14984] TFVC: tf add -noprompt -?
2020-07-02T17:47:20.546Z - debug:  [14984] TFVC: spawned new process (duration: 15ms)
2020-07-02T17:47:20.560Z - debug:  [14984] TFVC: spawned new process (duration: 13ms)
2020-07-02T17:47:21.286Z - debug:  [14984] TFVC: add exit code: 0 (duration: 756ms)
2020-07-02T17:47:21.288Z - debug:  [14984] TFVC Minimum required version: 14.102.0
2020-07-02T17:47:21.288Z - debug:  [14984] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-07-02T17:47:21.289Z - debug:  [14984] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-07-02T17:47:21.290Z - debug:  [14984] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-07-02T17:47:21.296Z - debug:  [14984] TFVC: spawned new process (duration: 6ms)
2020-07-02T17:47:21.571Z - debug:  [14984] TFVC: workfold exit code: 100 (duration: 281ms)
2020-07-02T17:47:21.574Z - debug:  [14984] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-07-02T17:47:21.575Z - error:  [14984] Execution of the TFVC command line failed unexpectedly.
2020-07-20T18:35:16.660Z - info:   [09960] *** FOLDER: y:\Test_Projects\Python ***
2020-07-20T18:35:16.662Z - info:   [09960] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-07-20T18:35:16.663Z - debug:  [09960] Looking for an External Context at y:\Test_Projects\Python
2020-07-20T18:35:16.663Z - debug:  [09960] No External Context at y:\Test_Projects\Python
2020-07-20T18:35:16.709Z - debug:  [09960] Looking for TFVC repository at y:\Test_Projects\Python
2020-07-20T18:35:16.710Z - debug:  [09960] TFVC Creating Tfvc object with localPath='undefined'
2020-07-20T18:35:16.711Z - debug:  [09960] Using TFS proxy: 
2020-07-20T18:35:16.712Z - debug:  [09960] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-07-20T18:35:16.722Z - debug:  [09960] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-07-20T18:35:16.722Z - debug:  [09960] TFVC Repository.CheckVersion
2020-07-20T18:35:16.723Z - debug:  [09960] TFVC: tf add -noprompt -?
2020-07-20T18:35:16.801Z - debug:  [09960] TFVC: spawned new process (duration: 77ms)
2020-07-20T18:35:16.807Z - debug:  [09960] TFVC: spawned new process (duration: 5ms)
2020-07-20T18:35:23.461Z - debug:  [09960] TFVC: add exit code: 0 (duration: 6737ms)
2020-07-20T18:35:23.464Z - debug:  [09960] TFVC Minimum required version: 14.102.0
2020-07-20T18:35:23.465Z - debug:  [09960] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-07-20T18:35:23.465Z - debug:  [09960] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-07-20T18:35:23.466Z - debug:  [09960] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-07-20T18:35:23.473Z - debug:  [09960] TFVC: spawned new process (duration: 6ms)
2020-07-20T18:35:32.495Z - debug:  [09960] TFVC: workfold exit code: 100 (duration: 9029ms)
2020-07-20T18:35:32.498Z - debug:  [09960] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-07-20T18:35:32.499Z - error:  [09960] Execution of the TFVC command line failed unexpectedly.
2020-09-08T15:36:15.364Z - info:   [17608] *** FOLDER: y:\Test_Projects\Python ***
2020-09-08T15:36:15.366Z - info:   [17608] AzureReposVSCode/1.161.0 (VSCode 1.46.1; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-08T15:36:15.367Z - debug:  [17608] Looking for an External Context at y:\Test_Projects\Python
2020-09-08T15:36:15.367Z - debug:  [17608] No External Context at y:\Test_Projects\Python
2020-09-08T15:36:15.386Z - debug:  [17608] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-08T15:36:15.387Z - debug:  [17608] TFVC Creating Tfvc object with localPath='undefined'
2020-09-08T15:36:15.388Z - debug:  [17608] Using TFS proxy: 
2020-09-08T15:36:15.388Z - debug:  [17608] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-08T15:36:15.476Z - debug:  [17608] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-08T15:36:15.479Z - debug:  [17608] TFVC Repository.CheckVersion
2020-09-08T15:36:15.479Z - debug:  [17608] TFVC: tf add -noprompt -?
2020-09-08T15:36:15.861Z - debug:  [17608] TFVC: spawned new process (duration: 380ms)
2020-09-08T15:36:15.878Z - debug:  [17608] TFVC: spawned new process (duration: 13ms)
2020-09-08T15:36:29.116Z - debug:  [17608] TFVC: add exit code: 0 (duration: 13636ms)
2020-09-08T15:36:29.119Z - debug:  [17608] TFVC Minimum required version: 14.102.0
2020-09-08T15:36:29.119Z - debug:  [17608] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-08T15:36:29.120Z - debug:  [17608] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-08T15:36:29.121Z - debug:  [17608] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-08T15:36:29.127Z - debug:  [17608] TFVC: spawned new process (duration: 6ms)
2020-09-08T15:36:32.293Z - debug:  [17608] TFVC: workfold exit code: 100 (duration: 3171ms)
2020-09-08T15:36:32.296Z - debug:  [17608] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-08T15:36:32.297Z - error:  [17608] Execution of the TFVC command line failed unexpectedly.
2020-09-08T16:53:52.323Z - info:   [12748] *** FOLDER: y:\Test_Projects\Python ***
2020-09-08T16:53:52.325Z - info:   [12748] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-08T16:53:52.326Z - debug:  [12748] Looking for an External Context at y:\Test_Projects\Python
2020-09-08T16:53:52.327Z - debug:  [12748] No External Context at y:\Test_Projects\Python
2020-09-08T16:53:52.471Z - debug:  [12748] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-08T16:53:52.471Z - debug:  [12748] TFVC Creating Tfvc object with localPath='undefined'
2020-09-08T16:53:52.473Z - debug:  [12748] Using TFS proxy: 
2020-09-08T16:53:52.473Z - debug:  [12748] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-08T16:53:52.600Z - debug:  [12748] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-08T16:53:52.602Z - debug:  [12748] TFVC Repository.CheckVersion
2020-09-08T16:53:52.604Z - debug:  [12748] TFVC: tf add -noprompt -?
2020-09-08T16:53:52.719Z - debug:  [12748] TFVC: spawned new process (duration: 112ms)
2020-09-08T16:53:52.727Z - debug:  [12748] TFVC: spawned new process (duration: 7ms)
2020-09-08T16:54:13.372Z - debug:  [12748] TFVC: add exit code: 0 (duration: 20768ms)
2020-09-08T16:54:13.374Z - debug:  [12748] TFVC Minimum required version: 14.102.0
2020-09-08T16:54:13.374Z - debug:  [12748] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-08T16:54:13.374Z - debug:  [12748] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-08T16:54:13.375Z - debug:  [12748] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-08T16:54:13.380Z - debug:  [12748] TFVC: spawned new process (duration: 4ms)
2020-09-08T16:54:32.335Z - debug:  [12748] TFVC: workfold exit code: 100 (duration: 18960ms)
2020-09-08T16:54:32.338Z - debug:  [12748] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-08T16:54:32.339Z - error:  [12748] Execution of the TFVC command line failed unexpectedly.
2020-09-08T16:55:38.968Z - debug:  [12748] Reinitializing due to onDidChangeConfiguration
2020-09-08T16:55:38.972Z - debug:  [12748] Polling interval value (minutes): 5
2020-09-08T16:55:38.972Z - debug:  [12748] Polling interval must be greater than 10 minutes.
2020-09-08T16:55:38.979Z - info:   [12748] *** FOLDER: y:\Test_Projects\Python ***
2020-09-08T16:55:38.980Z - info:   [12748] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-08T16:55:38.981Z - debug:  [12748] Looking for an External Context at y:\Test_Projects\Python
2020-09-08T16:55:38.982Z - debug:  [12748] No External Context at y:\Test_Projects\Python
2020-09-08T16:55:39.005Z - debug:  [12748] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-08T16:55:39.005Z - debug:  [12748] TFVC Creating Tfvc object with localPath='undefined'
2020-09-08T16:55:39.007Z - debug:  [12748] Using TFS proxy: 
2020-09-08T16:55:39.007Z - debug:  [12748] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-08T16:55:39.009Z - debug:  [12748] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-08T16:55:39.011Z - debug:  [12748] TFVC Repository.CheckVersion
2020-09-08T16:55:39.013Z - debug:  [12748] TFVC: tf add -noprompt -?
2020-09-08T16:55:39.021Z - debug:  [12748] TFVC: spawned new process (duration: 6ms)
2020-09-08T16:55:39.485Z - debug:  [12748] TFVC: add exit code: 0 (duration: 472ms)
2020-09-08T16:55:39.487Z - debug:  [12748] TFVC Minimum required version: 14.102.0
2020-09-08T16:55:39.488Z - debug:  [12748] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-08T16:55:39.488Z - debug:  [12748] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-08T16:55:39.489Z - debug:  [12748] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-08T16:55:39.495Z - debug:  [12748] TFVC: spawned new process (duration: 5ms)
2020-09-08T16:55:39.828Z - debug:  [12748] TFVC: workfold exit code: 100 (duration: 338ms)
2020-09-08T16:55:39.832Z - debug:  [12748] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-08T16:55:39.833Z - error:  [12748] Execution of the TFVC command line failed unexpectedly.
2020-09-13T13:47:56.052Z - info:   [09128] *** FOLDER: y:\Test_Projects\Python ***
2020-09-13T13:47:56.054Z - info:   [09128] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-13T13:47:56.055Z - debug:  [09128] Looking for an External Context at y:\Test_Projects\Python
2020-09-13T13:47:56.055Z - debug:  [09128] No External Context at y:\Test_Projects\Python
2020-09-13T13:47:56.057Z - debug:  [09128] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-13T13:47:56.058Z - debug:  [09128] TFVC Creating Tfvc object with localPath='undefined'
2020-09-13T13:47:56.059Z - debug:  [09128] Using TFS proxy: 
2020-09-13T13:47:56.059Z - debug:  [09128] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-13T13:47:56.434Z - debug:  [09128] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-13T13:47:56.437Z - debug:  [09128] TFVC Repository.CheckVersion
2020-09-13T13:47:56.439Z - debug:  [09128] TFVC: tf add -noprompt -?
2020-09-13T13:47:56.861Z - debug:  [09128] TFVC: spawned new process (duration: 420ms)
2020-09-13T13:47:56.869Z - debug:  [09128] TFVC: spawned new process (duration: 7ms)
2020-09-13T13:48:29.369Z - debug:  [09128] TFVC: add exit code: 0 (duration: 32929ms)
2020-09-13T13:48:29.372Z - debug:  [09128] TFVC Minimum required version: 14.102.0
2020-09-13T13:48:29.372Z - debug:  [09128] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-13T13:48:29.373Z - debug:  [09128] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-13T13:48:29.374Z - debug:  [09128] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-13T13:48:29.380Z - debug:  [09128] TFVC: spawned new process (duration: 6ms)
2020-09-13T13:48:47.905Z - debug:  [09128] TFVC: workfold exit code: 100 (duration: 18531ms)
2020-09-13T13:48:47.908Z - debug:  [09128] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-13T13:48:47.909Z - error:  [09128] Execution of the TFVC command line failed unexpectedly.
2020-09-13T16:24:53.563Z - info:   [16068] *** FOLDER: y:\Test_Projects\Python ***
2020-09-13T16:24:53.565Z - info:   [16068] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-13T16:24:53.566Z - debug:  [16068] Looking for an External Context at y:\Test_Projects\Python
2020-09-13T16:24:53.567Z - debug:  [16068] No External Context at y:\Test_Projects\Python
2020-09-13T16:24:53.569Z - debug:  [16068] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-13T16:24:53.570Z - debug:  [16068] TFVC Creating Tfvc object with localPath='undefined'
2020-09-13T16:24:53.572Z - debug:  [16068] Using TFS proxy: 
2020-09-13T16:24:53.572Z - debug:  [16068] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-13T16:24:53.574Z - debug:  [16068] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-13T16:24:53.576Z - debug:  [16068] TFVC Repository.CheckVersion
2020-09-13T16:24:53.577Z - debug:  [16068] TFVC: tf add -noprompt -?
2020-09-13T16:24:53.585Z - debug:  [16068] TFVC: spawned new process (duration: 6ms)
2020-09-13T16:24:53.608Z - debug:  [16068] TFVC: spawned new process (duration: 22ms)
2020-09-13T16:24:55.177Z - debug:  [16068] TFVC: add exit code: 0 (duration: 1599ms)
2020-09-13T16:24:55.179Z - debug:  [16068] TFVC Minimum required version: 14.102.0
2020-09-13T16:24:55.179Z - debug:  [16068] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-13T16:24:55.180Z - debug:  [16068] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-13T16:24:55.181Z - debug:  [16068] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-13T16:24:55.187Z - debug:  [16068] TFVC: spawned new process (duration: 5ms)
2020-09-13T16:24:55.555Z - debug:  [16068] TFVC: workfold exit code: 100 (duration: 374ms)
2020-09-13T16:24:55.559Z - debug:  [16068] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-13T16:24:55.560Z - error:  [16068] Execution of the TFVC command line failed unexpectedly.
2020-09-17T15:46:56.563Z - info:   [11096] *** FOLDER: y:\Test_Projects\Python ***
2020-09-17T15:46:56.565Z - info:   [11096] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-17T15:46:56.566Z - debug:  [11096] Looking for an External Context at y:\Test_Projects\Python
2020-09-17T15:46:56.567Z - debug:  [11096] No External Context at y:\Test_Projects\Python
2020-09-17T15:46:56.569Z - debug:  [11096] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-17T15:46:56.569Z - debug:  [11096] TFVC Creating Tfvc object with localPath='undefined'
2020-09-17T15:46:56.571Z - debug:  [11096] Using TFS proxy: 
2020-09-17T15:46:56.571Z - debug:  [11096] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-17T15:46:56.572Z - debug:  [11096] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-17T15:46:56.573Z - debug:  [11096] TFVC Repository.CheckVersion
2020-09-17T15:46:56.574Z - debug:  [11096] TFVC: tf add -noprompt -?
2020-09-17T15:46:56.647Z - debug:  [11096] TFVC: spawned new process (duration: 71ms)
2020-09-17T15:46:56.655Z - debug:  [11096] TFVC: spawned new process (duration: 7ms)
2020-09-17T15:47:06.529Z - debug:  [11096] TFVC: add exit code: 0 (duration: 9954ms)
2020-09-17T15:47:06.532Z - debug:  [11096] TFVC Minimum required version: 14.102.0
2020-09-17T15:47:06.532Z - debug:  [11096] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-17T15:47:06.533Z - debug:  [11096] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-17T15:47:06.533Z - debug:  [11096] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-17T15:47:06.540Z - debug:  [11096] TFVC: spawned new process (duration: 6ms)
2020-09-17T15:47:12.032Z - debug:  [11096] TFVC: workfold exit code: 100 (duration: 5498ms)
2020-09-17T15:47:12.035Z - debug:  [11096] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-17T15:47:12.036Z - error:  [11096] Execution of the TFVC command line failed unexpectedly.
2020-09-18T07:59:02.181Z - info:   [0532] *** FOLDER: y:\Test_Projects\Python ***
2020-09-18T07:59:02.183Z - info:   [0532] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-18T07:59:02.184Z - debug:  [0532] Looking for an External Context at y:\Test_Projects\Python
2020-09-18T07:59:02.185Z - debug:  [0532] No External Context at y:\Test_Projects\Python
2020-09-18T07:59:02.187Z - debug:  [0532] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-18T07:59:02.188Z - debug:  [0532] TFVC Creating Tfvc object with localPath='undefined'
2020-09-18T07:59:02.190Z - debug:  [0532] Using TFS proxy: 
2020-09-18T07:59:02.190Z - debug:  [0532] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-18T07:59:02.242Z - debug:  [0532] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-18T07:59:02.243Z - debug:  [0532] TFVC Repository.CheckVersion
2020-09-18T07:59:02.245Z - debug:  [0532] TFVC: tf add -noprompt -?
2020-09-18T07:59:02.306Z - debug:  [0532] TFVC: spawned new process (duration: 59ms)
2020-09-18T07:59:02.314Z - debug:  [0532] TFVC: spawned new process (duration: 7ms)
2020-09-18T07:59:11.483Z - debug:  [0532] TFVC: add exit code: 0 (duration: 9238ms)
2020-09-18T07:59:11.484Z - debug:  [0532] TFVC Minimum required version: 14.102.0
2020-09-18T07:59:11.485Z - debug:  [0532] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-18T07:59:11.485Z - debug:  [0532] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-18T07:59:11.486Z - debug:  [0532] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-18T07:59:11.509Z - debug:  [0532] TFVC: spawned new process (duration: 21ms)
2020-09-18T07:59:14.442Z - debug:  [0532] TFVC: workfold exit code: 100 (duration: 2955ms)
2020-09-18T07:59:14.444Z - debug:  [0532] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-18T07:59:14.445Z - error:  [0532] Execution of the TFVC command line failed unexpectedly.
2020-09-24T13:54:35.274Z - info:   [11608] *** FOLDER: y:\Test_Projects\Python ***
2020-09-24T13:54:35.276Z - info:   [11608] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-24T13:54:35.277Z - debug:  [11608] Looking for an External Context at y:\Test_Projects\Python
2020-09-24T13:54:35.277Z - debug:  [11608] No External Context at y:\Test_Projects\Python
2020-09-24T13:54:35.279Z - debug:  [11608] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-24T13:54:35.279Z - debug:  [11608] TFVC Creating Tfvc object with localPath='undefined'
2020-09-24T13:54:35.281Z - debug:  [11608] Using TFS proxy: 
2020-09-24T13:54:35.281Z - debug:  [11608] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-24T13:54:35.430Z - debug:  [11608] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-24T13:54:35.431Z - debug:  [11608] TFVC Repository.CheckVersion
2020-09-24T13:54:35.433Z - debug:  [11608] TFVC: tf add -noprompt -?
2020-09-24T13:54:35.684Z - debug:  [11608] TFVC: spawned new process (duration: 250ms)
2020-09-24T13:54:35.694Z - debug:  [11608] TFVC: spawned new process (duration: 9ms)
2020-09-24T13:54:51.883Z - debug:  [11608] TFVC: add exit code: 0 (duration: 16450ms)
2020-09-24T13:54:51.885Z - debug:  [11608] TFVC Minimum required version: 14.102.0
2020-09-24T13:54:51.886Z - debug:  [11608] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-24T13:54:51.886Z - debug:  [11608] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-24T13:54:51.887Z - debug:  [11608] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-24T13:54:51.894Z - debug:  [11608] TFVC: spawned new process (duration: 6ms)
2020-09-24T13:55:02.278Z - debug:  [11608] TFVC: workfold exit code: 100 (duration: 10391ms)
2020-09-24T13:55:02.281Z - debug:  [11608] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-24T13:55:02.282Z - error:  [11608] Execution of the TFVC command line failed unexpectedly.
2020-09-24T13:57:35.674Z - info:   [09312] *** FOLDER: y:\Test_Projects\Python ***
2020-09-24T13:57:35.676Z - info:   [09312] AzureReposVSCode/1.161.0 (VSCode 1.48.2; Windows_NT 10.0.17134; Node 12.8.1)
2020-09-24T13:57:35.677Z - debug:  [09312] Looking for an External Context at y:\Test_Projects\Python
2020-09-24T13:57:35.677Z - debug:  [09312] No External Context at y:\Test_Projects\Python
2020-09-24T13:57:35.680Z - debug:  [09312] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-24T13:57:35.680Z - debug:  [09312] TFVC Creating Tfvc object with localPath='undefined'
2020-09-24T13:57:35.682Z - debug:  [09312] Using TFS proxy: 
2020-09-24T13:57:35.682Z - debug:  [09312] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-24T13:57:35.683Z - debug:  [09312] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-24T13:57:35.684Z - debug:  [09312] TFVC Repository.CheckVersion
2020-09-24T13:57:35.699Z - debug:  [09312] TFVC: tf add -noprompt -?
2020-09-24T13:57:35.709Z - debug:  [09312] TFVC: spawned new process (duration: 7ms)
2020-09-24T13:57:35.717Z - debug:  [09312] TFVC: spawned new process (duration: 7ms)
2020-09-24T13:57:38.219Z - debug:  [09312] TFVC: add exit code: 0 (duration: 2520ms)
2020-09-24T13:57:38.221Z - debug:  [09312] TFVC Minimum required version: 14.102.0
2020-09-24T13:57:38.221Z - debug:  [09312] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-24T13:57:38.222Z - debug:  [09312] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-24T13:57:38.223Z - debug:  [09312] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-24T13:57:38.229Z - debug:  [09312] TFVC: spawned new process (duration: 5ms)
2020-09-24T13:57:38.890Z - debug:  [09312] TFVC: workfold exit code: 100 (duration: 667ms)
2020-09-24T13:57:38.893Z - debug:  [09312] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-24T13:57:38.894Z - error:  [09312] Execution of the TFVC command line failed unexpectedly.
2020-09-24T14:00:05.841Z - info:   [15248] *** FOLDER: y:\Test_Projects\Python ***
2020-09-24T14:00:05.843Z - info:   [15248] AzureReposVSCode/1.161.0 (VSCode 1.49.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-09-24T14:00:05.845Z - debug:  [15248] Looking for an External Context at y:\Test_Projects\Python
2020-09-24T14:00:05.845Z - debug:  [15248] No External Context at y:\Test_Projects\Python
2020-09-24T14:00:05.848Z - debug:  [15248] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-24T14:00:05.848Z - debug:  [15248] TFVC Creating Tfvc object with localPath='undefined'
2020-09-24T14:00:05.850Z - debug:  [15248] Using TFS proxy: 
2020-09-24T14:00:05.850Z - debug:  [15248] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-24T14:00:05.851Z - debug:  [15248] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-24T14:00:05.852Z - debug:  [15248] TFVC Repository.CheckVersion
2020-09-24T14:00:05.854Z - debug:  [15248] TFVC: tf add -noprompt -?
2020-09-24T14:00:05.863Z - debug:  [15248] TFVC: spawned new process (duration: 8ms)
2020-09-24T14:00:05.871Z - debug:  [15248] TFVC: spawned new process (duration: 7ms)
2020-09-24T14:00:09.057Z - debug:  [15248] TFVC: add exit code: 0 (duration: 3202ms)
2020-09-24T14:00:09.058Z - debug:  [15248] TFVC Minimum required version: 14.102.0
2020-09-24T14:00:09.058Z - debug:  [15248] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-24T14:00:09.059Z - debug:  [15248] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-24T14:00:09.060Z - debug:  [15248] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-24T14:00:09.068Z - debug:  [15248] TFVC: spawned new process (duration: 7ms)
2020-09-24T14:00:09.832Z - debug:  [15248] TFVC: workfold exit code: 100 (duration: 772ms)
2020-09-24T14:00:09.834Z - debug:  [15248] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-24T14:00:09.836Z - error:  [15248] Execution of the TFVC command line failed unexpectedly.
2020-09-29T15:29:21.991Z - info:   [07252] *** FOLDER: y:\Test_Projects\Python ***
2020-09-29T15:29:21.993Z - info:   [07252] AzureReposVSCode/1.161.0 (VSCode 1.49.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-09-29T15:29:21.994Z - debug:  [07252] Looking for an External Context at y:\Test_Projects\Python
2020-09-29T15:29:21.994Z - debug:  [07252] No External Context at y:\Test_Projects\Python
2020-09-29T15:29:21.995Z - debug:  [07252] Looking for TFVC repository at y:\Test_Projects\Python
2020-09-29T15:29:21.996Z - debug:  [07252] TFVC Creating Tfvc object with localPath='undefined'
2020-09-29T15:29:21.997Z - debug:  [07252] Using TFS proxy: 
2020-09-29T15:29:21.997Z - debug:  [07252] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-09-29T15:29:22.070Z - debug:  [07252] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-09-29T15:29:22.071Z - debug:  [07252] TFVC Repository.CheckVersion
2020-09-29T15:29:22.072Z - debug:  [07252] TFVC: tf add -noprompt -?
2020-09-29T15:29:22.400Z - debug:  [07252] TFVC: spawned new process (duration: 326ms)
2020-09-29T15:29:22.556Z - debug:  [07252] TFVC: spawned new process (duration: 155ms)
2020-09-29T15:29:55.124Z - debug:  [07252] TFVC: add exit code: 0 (duration: 33051ms)
2020-09-29T15:29:55.126Z - debug:  [07252] TFVC Minimum required version: 14.102.0
2020-09-29T15:29:55.126Z - debug:  [07252] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-09-29T15:29:55.127Z - debug:  [07252] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-09-29T15:29:55.127Z - debug:  [07252] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-09-29T15:29:55.134Z - debug:  [07252] TFVC: spawned new process (duration: 5ms)
2020-09-29T15:30:05.539Z - debug:  [07252] TFVC: workfold exit code: 100 (duration: 10412ms)
2020-09-29T15:30:05.542Z - debug:  [07252] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-09-29T15:30:05.543Z - error:  [07252] Execution of the TFVC command line failed unexpectedly.
2020-10-01T14:34:11.530Z - info:   [16056] *** FOLDER: y:\Test_Projects\Python ***
2020-10-01T14:34:11.532Z - info:   [16056] AzureReposVSCode/1.161.0 (VSCode 1.49.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-01T14:34:11.533Z - debug:  [16056] Looking for an External Context at y:\Test_Projects\Python
2020-10-01T14:34:11.533Z - debug:  [16056] No External Context at y:\Test_Projects\Python
2020-10-01T14:34:11.536Z - debug:  [16056] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-01T14:34:11.537Z - debug:  [16056] TFVC Creating Tfvc object with localPath='undefined'
2020-10-01T14:34:11.538Z - debug:  [16056] Using TFS proxy: 
2020-10-01T14:34:11.538Z - debug:  [16056] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-01T14:34:12.077Z - debug:  [16056] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-01T14:34:12.078Z - debug:  [16056] TFVC Repository.CheckVersion
2020-10-01T14:34:12.080Z - debug:  [16056] TFVC: tf add -noprompt -?
2020-10-01T14:34:12.902Z - debug:  [16056] TFVC: spawned new process (duration: 819ms)
2020-10-01T14:34:12.914Z - debug:  [16056] TFVC: spawned new process (duration: 10ms)
2020-10-01T14:34:46.072Z - debug:  [16056] TFVC: add exit code: 0 (duration: 33991ms)
2020-10-01T14:34:46.074Z - debug:  [16056] TFVC Minimum required version: 14.102.0
2020-10-01T14:34:46.074Z - debug:  [16056] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-01T14:34:46.074Z - debug:  [16056] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-01T14:34:46.075Z - debug:  [16056] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-01T14:34:46.081Z - debug:  [16056] TFVC: spawned new process (duration: 5ms)
2020-10-01T14:35:04.047Z - debug:  [16056] TFVC: workfold exit code: 100 (duration: 17972ms)
2020-10-01T14:35:04.050Z - debug:  [16056] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-01T14:35:04.051Z - error:  [16056] Execution of the TFVC command line failed unexpectedly.
2020-10-04T07:43:01.953Z - info:   [15472] *** FOLDER: y:\Test_Projects\Python ***
2020-10-04T07:43:01.955Z - info:   [15472] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-04T07:43:01.957Z - debug:  [15472] Looking for an External Context at y:\Test_Projects\Python
2020-10-04T07:43:01.957Z - debug:  [15472] No External Context at y:\Test_Projects\Python
2020-10-04T07:43:01.959Z - debug:  [15472] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-04T07:43:01.960Z - debug:  [15472] TFVC Creating Tfvc object with localPath='undefined'
2020-10-04T07:43:01.961Z - debug:  [15472] Using TFS proxy: 
2020-10-04T07:43:01.961Z - debug:  [15472] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-04T07:43:01.988Z - debug:  [15472] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-04T07:43:01.989Z - debug:  [15472] TFVC Repository.CheckVersion
2020-10-04T07:43:01.990Z - debug:  [15472] TFVC: tf add -noprompt -?
2020-10-04T07:43:02.029Z - debug:  [15472] TFVC: spawned new process (duration: 37ms)
2020-10-04T07:43:02.037Z - debug:  [15472] TFVC: spawned new process (duration: 7ms)
2020-10-04T07:43:04.468Z - debug:  [15472] TFVC: add exit code: 0 (duration: 2476ms)
2020-10-04T07:43:04.470Z - debug:  [15472] TFVC Minimum required version: 14.102.0
2020-10-04T07:43:04.470Z - debug:  [15472] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-04T07:43:04.471Z - debug:  [15472] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-04T07:43:04.471Z - debug:  [15472] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-04T07:43:04.479Z - debug:  [15472] TFVC: spawned new process (duration: 7ms)
2020-10-04T07:43:06.490Z - debug:  [15472] TFVC: workfold exit code: 100 (duration: 2018ms)
2020-10-04T07:43:06.493Z - debug:  [15472] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-04T07:43:06.495Z - error:  [15472] Execution of the TFVC command line failed unexpectedly.
2020-10-04T16:40:45.041Z - info:   [02888] *** FOLDER: y:\Test_Projects\Python ***
2020-10-04T16:40:45.043Z - info:   [02888] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-04T16:40:45.044Z - debug:  [02888] Looking for an External Context at y:\Test_Projects\Python
2020-10-04T16:40:45.044Z - debug:  [02888] No External Context at y:\Test_Projects\Python
2020-10-04T16:40:45.046Z - debug:  [02888] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-04T16:40:45.047Z - debug:  [02888] TFVC Creating Tfvc object with localPath='undefined'
2020-10-04T16:40:45.048Z - debug:  [02888] Using TFS proxy: 
2020-10-04T16:40:45.048Z - debug:  [02888] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-04T16:40:45.049Z - debug:  [02888] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-04T16:40:45.051Z - debug:  [02888] TFVC Repository.CheckVersion
2020-10-04T16:40:45.052Z - debug:  [02888] TFVC: tf add -noprompt -?
2020-10-04T16:40:45.058Z - debug:  [02888] TFVC: spawned new process (duration: 5ms)
2020-10-04T16:40:45.065Z - debug:  [02888] TFVC: spawned new process (duration: 6ms)
2020-10-04T16:40:46.536Z - debug:  [02888] TFVC: add exit code: 0 (duration: 1484ms)
2020-10-04T16:40:46.538Z - debug:  [02888] TFVC Minimum required version: 14.102.0
2020-10-04T16:40:46.538Z - debug:  [02888] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-04T16:40:46.538Z - debug:  [02888] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-04T16:40:46.539Z - debug:  [02888] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-04T16:40:46.545Z - debug:  [02888] TFVC: spawned new process (duration: 4ms)
2020-10-04T16:40:47.318Z - debug:  [02888] TFVC: workfold exit code: 100 (duration: 779ms)
2020-10-04T16:40:47.321Z - debug:  [02888] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-04T16:40:47.322Z - error:  [02888] Execution of the TFVC command line failed unexpectedly.
2020-10-08T15:05:08.512Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-08T15:05:08.514Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-08T15:05:08.515Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-08T15:05:08.515Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-08T15:05:08.527Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-08T15:05:08.527Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-08T15:05:08.529Z - debug:  [14436] Using TFS proxy: 
2020-10-08T15:05:08.529Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-08T15:05:08.613Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-08T15:05:08.615Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-08T15:05:08.616Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-08T15:05:08.684Z - debug:  [14436] TFVC: spawned new process (duration: 67ms)
2020-10-08T15:05:08.691Z - debug:  [14436] TFVC: spawned new process (duration: 6ms)
2020-10-08T15:05:14.855Z - debug:  [14436] TFVC: add exit code: 0 (duration: 6237ms)
2020-10-08T15:05:14.857Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-08T15:05:14.857Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-08T15:05:14.858Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-08T15:05:14.858Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-08T15:05:14.865Z - debug:  [14436] TFVC: spawned new process (duration: 6ms)
2020-10-08T15:05:18.283Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 3424ms)
2020-10-08T15:05:18.284Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-08T15:05:18.285Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-12T02:49:41.110Z - debug:  [14436] Reinitializing due to onDidChangeConfiguration
2020-10-12T02:49:41.588Z - debug:  [14436] Polling interval value (minutes): 5
2020-10-12T02:49:41.589Z - debug:  [14436] Polling interval must be greater than 10 minutes.
2020-10-12T02:49:42.714Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-12T02:49:42.715Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-12T02:49:42.924Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-12T02:49:42.924Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-12T02:49:43.340Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-12T02:49:43.341Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-12T02:49:43.343Z - debug:  [14436] Using TFS proxy: 
2020-10-12T02:49:43.344Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-12T02:49:43.371Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-12T02:49:43.372Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-12T02:49:43.469Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-12T02:49:44.053Z - debug:  [14436] TFVC: spawned new process (duration: 498ms)
2020-10-12T02:49:55.307Z - debug:  [14436] TFVC: add exit code: 0 (duration: 11814ms)
2020-10-12T02:49:55.309Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-12T02:49:55.310Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-12T02:49:55.310Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-12T02:49:55.313Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-12T02:49:55.319Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T02:49:59.328Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 4015ms)
2020-10-12T02:49:59.331Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-12T02:49:59.332Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-12T02:51:05.030Z - debug:  [14436] Reinitializing due to onDidChangeConfiguration
2020-10-12T02:51:05.031Z - debug:  [14436] Polling interval value (minutes): 5
2020-10-12T02:51:05.031Z - debug:  [14436] Polling interval must be greater than 10 minutes.
2020-10-12T02:51:05.036Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-12T02:51:05.036Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-12T02:51:05.036Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-12T02:51:05.037Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-12T02:51:05.041Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-12T02:51:05.042Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-12T02:51:05.042Z - debug:  [14436] Using TFS proxy: 
2020-10-12T02:51:05.042Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-12T02:51:05.043Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-12T02:51:05.044Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-12T02:51:05.044Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-12T02:51:05.050Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T02:51:05.206Z - debug:  [14436] TFVC: add exit code: 0 (duration: 162ms)
2020-10-12T02:51:05.206Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-12T02:51:05.207Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-12T02:51:05.207Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-12T02:51:05.207Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-12T02:51:05.213Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T02:51:05.873Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 665ms)
2020-10-12T02:51:05.876Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-12T02:51:05.877Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-12T02:51:41.011Z - debug:  [14436] Reinitializing due to onDidChangeConfiguration
2020-10-12T02:51:41.013Z - debug:  [14436] Polling interval value (minutes): 5
2020-10-12T02:51:41.013Z - debug:  [14436] Polling interval must be greater than 10 minutes.
2020-10-12T02:51:41.016Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-12T02:51:41.016Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-12T02:51:41.016Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-12T02:51:41.017Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-12T02:51:41.028Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-12T02:51:41.028Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-12T02:51:41.029Z - debug:  [14436] Using TFS proxy: 
2020-10-12T02:51:41.029Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-12T02:51:41.030Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-12T02:51:41.031Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-12T02:51:41.031Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-12T02:51:41.037Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T02:51:41.219Z - debug:  [14436] TFVC: add exit code: 0 (duration: 188ms)
2020-10-12T02:51:41.220Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-12T02:51:41.220Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-12T02:51:41.220Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-12T02:51:41.221Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-12T02:51:41.227Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T02:51:41.980Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 759ms)
2020-10-12T02:51:41.980Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-12T02:51:41.981Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-12T15:00:43.109Z - debug:  [14436] Reinitializing due to onDidChangeConfiguration
2020-10-12T15:00:43.111Z - debug:  [14436] Polling interval value (minutes): 5
2020-10-12T15:00:43.111Z - debug:  [14436] Polling interval must be greater than 10 minutes.
2020-10-12T15:00:43.119Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-12T15:00:43.119Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-12T15:00:43.120Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-12T15:00:43.120Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-12T15:00:43.131Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-12T15:00:43.131Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-12T15:00:43.131Z - debug:  [14436] Using TFS proxy: 
2020-10-12T15:00:43.132Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-12T15:00:43.132Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-12T15:00:43.133Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-12T15:00:43.133Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-12T15:00:43.141Z - debug:  [14436] TFVC: spawned new process (duration: 7ms)
2020-10-12T15:00:45.338Z - debug:  [14436] TFVC: add exit code: 0 (duration: 2203ms)
2020-10-12T15:00:45.338Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-12T15:00:45.338Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-12T15:00:45.339Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-12T15:00:45.339Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-12T15:00:45.346Z - debug:  [14436] TFVC: spawned new process (duration: 6ms)
2020-10-12T15:00:49.888Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 4549ms)
2020-10-12T15:00:49.889Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-12T15:00:49.889Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-12T15:48:30.836Z - debug:  [14436] Reinitializing due to onDidChangeConfiguration
2020-10-12T15:48:30.839Z - debug:  [14436] Polling interval value (minutes): 5
2020-10-12T15:48:30.839Z - debug:  [14436] Polling interval must be greater than 10 minutes.
2020-10-12T15:48:30.847Z - info:   [14436] *** FOLDER: y:\Test_Projects\Python ***
2020-10-12T15:48:30.848Z - info:   [14436] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-12T15:48:30.849Z - debug:  [14436] Looking for an External Context at y:\Test_Projects\Python
2020-10-12T15:48:30.850Z - debug:  [14436] No External Context at y:\Test_Projects\Python
2020-10-12T15:48:30.903Z - debug:  [14436] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-12T15:48:30.904Z - debug:  [14436] TFVC Creating Tfvc object with localPath='undefined'
2020-10-12T15:48:30.906Z - debug:  [14436] Using TFS proxy: 
2020-10-12T15:48:30.906Z - debug:  [14436] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-12T15:48:30.907Z - debug:  [14436] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-12T15:48:30.908Z - debug:  [14436] TFVC Repository.CheckVersion
2020-10-12T15:48:30.910Z - debug:  [14436] TFVC: tf add -noprompt -?
2020-10-12T15:48:30.929Z - debug:  [14436] TFVC: spawned new process (duration: 9ms)
2020-10-12T15:48:31.163Z - debug:  [14436] TFVC: add exit code: 0 (duration: 253ms)
2020-10-12T15:48:31.166Z - debug:  [14436] TFVC Minimum required version: 14.102.0
2020-10-12T15:48:31.166Z - debug:  [14436] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-12T15:48:31.166Z - debug:  [14436] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-12T15:48:31.167Z - debug:  [14436] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-12T15:48:31.173Z - debug:  [14436] TFVC: spawned new process (duration: 5ms)
2020-10-12T15:48:32.516Z - debug:  [14436] TFVC: workfold exit code: 100 (duration: 1349ms)
2020-10-12T15:48:32.519Z - debug:  [14436] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-12T15:48:32.520Z - error:  [14436] Execution of the TFVC command line failed unexpectedly.
2020-10-14T09:37:14.578Z - info:   [16112] *** FOLDER: y:\Test_Projects\Python ***
2020-10-14T09:37:14.579Z - info:   [16112] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-14T09:37:14.580Z - debug:  [16112] Looking for an External Context at y:\Test_Projects\Python
2020-10-14T09:37:14.580Z - debug:  [16112] No External Context at y:\Test_Projects\Python
2020-10-14T09:37:14.739Z - debug:  [16112] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-14T09:37:14.740Z - debug:  [16112] TFVC Creating Tfvc object with localPath='undefined'
2020-10-14T09:37:14.744Z - debug:  [16112] Using TFS proxy: 
2020-10-14T09:37:14.744Z - debug:  [16112] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-14T09:37:14.856Z - debug:  [16112] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-14T09:37:14.857Z - debug:  [16112] TFVC Repository.CheckVersion
2020-10-14T09:37:14.859Z - debug:  [16112] TFVC: tf add -noprompt -?
2020-10-14T09:37:15.006Z - debug:  [16112] TFVC: spawned new process (duration: 145ms)
2020-10-14T09:37:15.030Z - debug:  [16112] TFVC: spawned new process (duration: 21ms)
2020-10-14T09:37:40.101Z - debug:  [16112] TFVC: add exit code: 0 (duration: 25242ms)
2020-10-14T09:37:40.103Z - debug:  [16112] TFVC Minimum required version: 14.102.0
2020-10-14T09:37:40.103Z - debug:  [16112] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-14T09:37:40.104Z - debug:  [16112] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-14T09:37:40.104Z - debug:  [16112] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-14T09:37:40.123Z - debug:  [16112] TFVC: spawned new process (duration: 18ms)
2020-10-14T09:37:50.866Z - debug:  [16112] TFVC: workfold exit code: 100 (duration: 10759ms)
2020-10-14T09:37:50.870Z - debug:  [16112] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-14T09:37:50.872Z - error:  [16112] Execution of the TFVC command line failed unexpectedly.
2020-10-14T17:04:23.221Z - debug:  [16112] Reinitializing due to onDidChangeConfiguration
2020-10-14T17:04:23.225Z - debug:  [16112] Polling interval value (minutes): 5
2020-10-14T17:04:23.225Z - debug:  [16112] Polling interval must be greater than 10 minutes.
2020-10-14T17:04:23.235Z - info:   [16112] *** FOLDER: y:\Test_Projects\Python ***
2020-10-14T17:04:23.235Z - info:   [16112] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-14T17:04:23.237Z - debug:  [16112] Looking for an External Context at y:\Test_Projects\Python
2020-10-14T17:04:23.237Z - debug:  [16112] No External Context at y:\Test_Projects\Python
2020-10-14T17:04:23.256Z - debug:  [16112] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-14T17:04:23.257Z - debug:  [16112] TFVC Creating Tfvc object with localPath='undefined'
2020-10-14T17:04:23.260Z - debug:  [16112] Using TFS proxy: 
2020-10-14T17:04:23.260Z - debug:  [16112] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-14T17:04:23.261Z - debug:  [16112] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-14T17:04:23.262Z - debug:  [16112] TFVC Repository.CheckVersion
2020-10-14T17:04:23.264Z - debug:  [16112] TFVC: tf add -noprompt -?
2020-10-14T17:04:23.303Z - debug:  [16112] TFVC: spawned new process (duration: 37ms)
2020-10-14T17:04:23.915Z - debug:  [16112] TFVC: add exit code: 0 (duration: 651ms)
2020-10-14T17:04:23.917Z - debug:  [16112] TFVC Minimum required version: 14.102.0
2020-10-14T17:04:23.917Z - debug:  [16112] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-14T17:04:23.918Z - debug:  [16112] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-14T17:04:23.918Z - debug:  [16112] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-14T17:04:23.924Z - debug:  [16112] TFVC: spawned new process (duration: 5ms)
2020-10-14T17:04:25.774Z - debug:  [16112] TFVC: workfold exit code: 100 (duration: 1854ms)
2020-10-14T17:04:25.776Z - debug:  [16112] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-14T17:04:25.777Z - error:  [16112] Execution of the TFVC command line failed unexpectedly.
2020-10-15T15:29:34.902Z - info:   [08480] *** FOLDER: y:\Test_Projects\Python ***
2020-10-15T15:29:34.903Z - info:   [08480] AzureReposVSCode/1.161.1 (VSCode 1.49.3; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-15T15:29:34.904Z - debug:  [08480] Looking for an External Context at y:\Test_Projects\Python
2020-10-15T15:29:34.905Z - debug:  [08480] No External Context at y:\Test_Projects\Python
2020-10-15T15:29:34.917Z - debug:  [08480] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-15T15:29:34.918Z - debug:  [08480] TFVC Creating Tfvc object with localPath='undefined'
2020-10-15T15:29:34.920Z - debug:  [08480] Using TFS proxy: 
2020-10-15T15:29:34.920Z - debug:  [08480] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-15T15:29:34.921Z - debug:  [08480] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-15T15:29:34.922Z - debug:  [08480] TFVC Repository.CheckVersion
2020-10-15T15:29:34.924Z - debug:  [08480] TFVC: tf add -noprompt -?
2020-10-15T15:29:35.050Z - debug:  [08480] TFVC: spawned new process (duration: 125ms)
2020-10-15T15:29:35.069Z - debug:  [08480] TFVC: spawned new process (duration: 18ms)
2020-10-15T15:29:43.527Z - debug:  [08480] TFVC: add exit code: 0 (duration: 8603ms)
2020-10-15T15:29:43.531Z - debug:  [08480] TFVC Minimum required version: 14.102.0
2020-10-15T15:29:43.531Z - debug:  [08480] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-15T15:29:43.531Z - debug:  [08480] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-15T15:29:43.533Z - debug:  [08480] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-15T15:29:43.539Z - debug:  [08480] TFVC: spawned new process (duration: 5ms)
2020-10-15T15:29:49.507Z - debug:  [08480] TFVC: workfold exit code: 100 (duration: 5974ms)
2020-10-15T15:29:49.510Z - debug:  [08480] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-15T15:29:49.511Z - error:  [08480] Execution of the TFVC command line failed unexpectedly.
2020-10-15T15:42:14.170Z - info:   [17900] *** FOLDER: y:\Test_Projects\Python ***
2020-10-15T15:42:14.171Z - info:   [17900] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-15T15:42:14.172Z - debug:  [17900] Looking for an External Context at y:\Test_Projects\Python
2020-10-15T15:42:14.173Z - debug:  [17900] No External Context at y:\Test_Projects\Python
2020-10-15T15:42:14.184Z - debug:  [17900] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-15T15:42:14.185Z - debug:  [17900] TFVC Creating Tfvc object with localPath='undefined'
2020-10-15T15:42:14.186Z - debug:  [17900] Using TFS proxy: 
2020-10-15T15:42:14.187Z - debug:  [17900] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-15T15:42:14.188Z - debug:  [17900] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-15T15:42:14.189Z - debug:  [17900] TFVC Repository.CheckVersion
2020-10-15T15:42:14.190Z - debug:  [17900] TFVC: tf add -noprompt -?
2020-10-15T15:42:14.197Z - debug:  [17900] TFVC: spawned new process (duration: 5ms)
2020-10-15T15:42:14.212Z - debug:  [17900] TFVC: spawned new process (duration: 14ms)
2020-10-15T15:42:19.245Z - debug:  [17900] TFVC: add exit code: 0 (duration: 5054ms)
2020-10-15T15:42:19.250Z - debug:  [17900] TFVC Minimum required version: 14.102.0
2020-10-15T15:42:19.250Z - debug:  [17900] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-15T15:42:19.250Z - debug:  [17900] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-15T15:42:19.250Z - debug:  [17900] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-15T15:42:19.263Z - debug:  [17900] TFVC: spawned new process (duration: 7ms)
2020-10-15T15:42:20.914Z - debug:  [17900] TFVC: workfold exit code: 100 (duration: 1663ms)
2020-10-15T15:42:20.916Z - debug:  [17900] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-15T15:42:20.917Z - error:  [17900] Execution of the TFVC command line failed unexpectedly.
2020-10-18T06:05:02.535Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-18T06:05:02.535Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-18T06:05:02.535Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-18T06:05:02.535Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-18T06:05:02.582Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-18T06:05:02.582Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-18T06:05:02.582Z - debug:  [13908] Using TFS proxy: 
2020-10-18T06:05:02.582Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-18T06:05:02.722Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-18T06:05:02.722Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-18T06:05:02.722Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-18T06:05:02.816Z - debug:  [13908] TFVC: spawned new process (duration: 94ms)
2020-10-18T06:05:02.832Z - debug:  [13908] TFVC: spawned new process (duration: 0ms)
2020-10-18T06:05:14.214Z - debug:  [13908] TFVC: add exit code: 0 (duration: 11492ms)
2020-10-18T06:05:14.216Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-18T06:05:14.216Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-18T06:05:14.217Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-18T06:05:14.217Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-18T06:05:14.224Z - debug:  [13908] TFVC: spawned new process (duration: 6ms)
2020-10-18T06:05:21.948Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 7730ms)
2020-10-18T06:05:21.949Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-18T06:05:21.950Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-18T15:43:03.959Z - debug:  [13908] Reinitializing due to onDidChangeConfiguration
2020-10-18T15:43:03.964Z - debug:  [13908] Polling interval value (minutes): 5
2020-10-18T15:43:03.964Z - debug:  [13908] Polling interval must be greater than 10 minutes.
2020-10-18T15:43:03.972Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-18T15:43:03.972Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-18T15:43:03.974Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-18T15:43:03.974Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-18T15:43:04.000Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-18T15:43:04.000Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-18T15:43:04.001Z - debug:  [13908] Using TFS proxy: 
2020-10-18T15:43:04.001Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-18T15:43:04.003Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-18T15:43:04.004Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-18T15:43:04.006Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-18T15:43:04.019Z - debug:  [13908] TFVC: spawned new process (duration: 10ms)
2020-10-18T15:43:04.164Z - debug:  [13908] TFVC: add exit code: 0 (duration: 158ms)
2020-10-18T15:43:04.166Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-18T15:43:04.166Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-18T15:43:04.167Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-18T15:43:04.168Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-18T15:43:04.174Z - debug:  [13908] TFVC: spawned new process (duration: 5ms)
2020-10-18T15:43:04.996Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 828ms)
2020-10-18T15:43:04.998Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-18T15:43:04.999Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-19T14:19:57.246Z - debug:  [13908] Reinitializing due to onDidChangeConfiguration
2020-10-19T14:19:57.249Z - debug:  [13908] Polling interval value (minutes): 5
2020-10-19T14:19:57.249Z - debug:  [13908] Polling interval must be greater than 10 minutes.
2020-10-19T14:19:57.260Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-19T14:19:57.260Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-19T14:19:57.260Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-19T14:19:57.260Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-19T14:19:57.274Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-19T14:19:57.274Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-19T14:19:57.275Z - debug:  [13908] Using TFS proxy: 
2020-10-19T14:19:57.275Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-19T14:19:57.276Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-19T14:19:57.277Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-19T14:19:57.278Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-19T14:19:57.286Z - debug:  [13908] TFVC: spawned new process (duration: 7ms)
2020-10-19T14:19:57.426Z - debug:  [13908] TFVC: add exit code: 0 (duration: 148ms)
2020-10-19T14:19:57.426Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-19T14:19:57.426Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-19T14:19:57.427Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-19T14:19:57.427Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-19T14:19:57.434Z - debug:  [13908] TFVC: spawned new process (duration: 5ms)
2020-10-19T14:19:59.373Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 1946ms)
2020-10-19T14:19:59.376Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-19T14:19:59.383Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-19T14:20:03.168Z - debug:  [13908] Reinitializing due to onDidChangeConfiguration
2020-10-19T14:20:03.170Z - debug:  [13908] Polling interval value (minutes): 5
2020-10-19T14:20:03.170Z - debug:  [13908] Polling interval must be greater than 10 minutes.
2020-10-19T14:20:03.175Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-19T14:20:03.176Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-19T14:20:03.176Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-19T14:20:03.176Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-19T14:20:03.180Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-19T14:20:03.180Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-19T14:20:03.181Z - debug:  [13908] Using TFS proxy: 
2020-10-19T14:20:03.181Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-19T14:20:03.182Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-19T14:20:03.182Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-19T14:20:03.183Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-19T14:20:03.196Z - debug:  [13908] TFVC: spawned new process (duration: 13ms)
2020-10-19T14:20:03.336Z - debug:  [13908] TFVC: add exit code: 0 (duration: 152ms)
2020-10-19T14:20:03.336Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-19T14:20:03.336Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-19T14:20:03.337Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-19T14:20:03.337Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-19T14:20:03.343Z - debug:  [13908] TFVC: spawned new process (duration: 5ms)
2020-10-19T14:20:03.892Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 555ms)
2020-10-19T14:20:03.894Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-19T14:20:03.894Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-19T14:24:14.913Z - debug:  [13908] Reinitializing due to onDidChangeConfiguration
2020-10-19T14:24:14.914Z - debug:  [13908] Polling interval value (minutes): 5
2020-10-19T14:24:14.914Z - debug:  [13908] Polling interval must be greater than 10 minutes.
2020-10-19T14:24:14.917Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-19T14:24:14.918Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-19T14:24:14.918Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-19T14:24:14.918Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-19T14:24:15.040Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-19T14:24:15.041Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-19T14:24:15.041Z - debug:  [13908] Using TFS proxy: 
2020-10-19T14:24:15.041Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-19T14:24:15.042Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-19T14:24:15.043Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-19T14:24:15.043Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-19T14:24:15.058Z - debug:  [13908] TFVC: spawned new process (duration: 14ms)
2020-10-19T14:24:15.366Z - debug:  [13908] TFVC: add exit code: 0 (duration: 323ms)
2020-10-19T14:24:15.367Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-19T14:24:15.367Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-19T14:24:15.368Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-19T14:24:15.368Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-19T14:24:15.374Z - debug:  [13908] TFVC: spawned new process (duration: 5ms)
2020-10-19T14:24:16.649Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 1281ms)
2020-10-19T14:24:16.650Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-19T14:24:16.650Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-19T14:24:24.609Z - debug:  [13908] Reinitializing due to onDidChangeConfiguration
2020-10-19T14:24:24.610Z - debug:  [13908] Polling interval value (minutes): 5
2020-10-19T14:24:24.610Z - debug:  [13908] Polling interval must be greater than 10 minutes.
2020-10-19T14:24:24.615Z - info:   [13908] *** FOLDER: y:\Test_Projects\Python ***
2020-10-19T14:24:24.615Z - info:   [13908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-19T14:24:24.615Z - debug:  [13908] Looking for an External Context at y:\Test_Projects\Python
2020-10-19T14:24:24.615Z - debug:  [13908] No External Context at y:\Test_Projects\Python
2020-10-19T14:24:24.619Z - debug:  [13908] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-19T14:24:24.623Z - debug:  [13908] TFVC Creating Tfvc object with localPath='undefined'
2020-10-19T14:24:24.623Z - debug:  [13908] Using TFS proxy: 
2020-10-19T14:24:24.624Z - debug:  [13908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-19T14:24:24.624Z - debug:  [13908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-19T14:24:24.625Z - debug:  [13908] TFVC Repository.CheckVersion
2020-10-19T14:24:24.625Z - debug:  [13908] TFVC: tf add -noprompt -?
2020-10-19T14:24:24.633Z - debug:  [13908] TFVC: spawned new process (duration: 7ms)
2020-10-19T14:24:24.780Z - debug:  [13908] TFVC: add exit code: 0 (duration: 155ms)
2020-10-19T14:24:24.780Z - debug:  [13908] TFVC Minimum required version: 14.102.0
2020-10-19T14:24:24.780Z - debug:  [13908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-19T14:24:24.780Z - debug:  [13908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-19T14:24:24.781Z - debug:  [13908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-19T14:24:24.786Z - debug:  [13908] TFVC: spawned new process (duration: 5ms)
2020-10-19T14:24:25.561Z - debug:  [13908] TFVC: workfold exit code: 100 (duration: 780ms)
2020-10-19T14:24:25.561Z - debug:  [13908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-19T14:24:25.561Z - error:  [13908] Execution of the TFVC command line failed unexpectedly.
2020-10-19T16:39:21.665Z - info:   [14852] *** FOLDER: y:\Test_Projects\Python ***
2020-10-19T16:39:21.667Z - info:   [14852] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-19T16:39:21.667Z - debug:  [14852] Looking for an External Context at y:\Test_Projects\Python
2020-10-19T16:39:21.668Z - debug:  [14852] No External Context at y:\Test_Projects\Python
2020-10-19T16:39:21.693Z - debug:  [14852] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-19T16:39:21.693Z - debug:  [14852] TFVC Creating Tfvc object with localPath='undefined'
2020-10-19T16:39:21.694Z - debug:  [14852] Using TFS proxy: 
2020-10-19T16:39:21.694Z - debug:  [14852] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-19T16:39:21.695Z - debug:  [14852] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-19T16:39:21.696Z - debug:  [14852] TFVC Repository.CheckVersion
2020-10-19T16:39:21.697Z - debug:  [14852] TFVC: tf add -noprompt -?
2020-10-19T16:39:21.750Z - debug:  [14852] TFVC: spawned new process (duration: 52ms)
2020-10-19T16:39:21.755Z - debug:  [14852] TFVC: spawned new process (duration: 4ms)
2020-10-19T16:39:47.088Z - debug:  [14852] TFVC: add exit code: 0 (duration: 25391ms)
2020-10-19T16:39:47.090Z - debug:  [14852] TFVC Minimum required version: 14.102.0
2020-10-19T16:39:47.090Z - debug:  [14852] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-19T16:39:47.091Z - debug:  [14852] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-19T16:39:47.091Z - debug:  [14852] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-19T16:39:47.097Z - debug:  [14852] TFVC: spawned new process (duration: 5ms)
2020-10-19T16:39:48.262Z - debug:  [14852] TFVC: workfold exit code: 100 (duration: 1170ms)
2020-10-19T16:39:48.265Z - debug:  [14852] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-19T16:39:48.266Z - error:  [14852] Execution of the TFVC command line failed unexpectedly.
2020-10-21T09:56:31.156Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-21T09:56:31.158Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-21T09:56:31.158Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-21T09:56:31.158Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-21T09:56:31.184Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-21T09:56:31.184Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-21T09:56:31.186Z - debug:  [17696] Using TFS proxy: 
2020-10-21T09:56:31.186Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-21T09:56:31.224Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-21T09:56:31.226Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-21T09:56:31.227Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-21T09:56:31.263Z - debug:  [17696] TFVC: spawned new process (duration: 35ms)
2020-10-21T09:56:31.272Z - debug:  [17696] TFVC: spawned new process (duration: 6ms)
2020-10-21T09:56:43.404Z - debug:  [17696] TFVC: add exit code: 0 (duration: 12177ms)
2020-10-21T09:56:43.408Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-21T09:56:43.409Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-21T09:56:43.412Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-21T09:56:43.412Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-21T09:56:43.423Z - debug:  [17696] TFVC: spawned new process (duration: 9ms)
2020-10-21T09:56:49.527Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 6114ms)
2020-10-21T09:56:49.529Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-21T09:56:49.529Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-23T09:32:39.332Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T09:32:39.339Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T09:32:39.340Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T09:32:39.471Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T09:32:39.472Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T09:32:39.474Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T09:32:39.474Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T09:32:39.508Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T09:32:39.509Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T09:32:39.510Z - debug:  [17696] Using TFS proxy: 
2020-10-23T09:32:39.510Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T09:32:39.511Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T09:32:39.515Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T09:32:39.516Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T09:32:39.672Z - debug:  [17696] TFVC: spawned new process (duration: 154ms)
2020-10-23T09:32:41.636Z - debug:  [17696] TFVC: add exit code: 0 (duration: 2120ms)
2020-10-23T09:32:41.641Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-23T09:32:41.641Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-23T09:32:41.644Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-23T09:32:41.646Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-23T09:32:41.660Z - debug:  [17696] TFVC: spawned new process (duration: 11ms)
2020-10-23T09:32:47.019Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 5373ms)
2020-10-23T09:32:47.023Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-23T09:32:47.024Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-23T17:16:02.296Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T17:16:02.299Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T17:16:02.299Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T17:16:02.309Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T17:16:02.309Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T17:16:02.310Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T17:16:02.310Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T17:16:02.328Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T17:16:02.329Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T17:16:02.330Z - debug:  [17696] Using TFS proxy: 
2020-10-23T17:16:02.330Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T17:16:02.331Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T17:16:02.333Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T17:16:02.336Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T17:16:02.425Z - debug:  [17696] TFVC: spawned new process (duration: 88ms)
2020-10-23T17:16:04.120Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T17:16:04.121Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T17:16:04.121Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T17:16:04.124Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T17:16:04.125Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T17:16:04.125Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T17:16:04.125Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T17:16:04.135Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T17:16:04.135Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T17:16:04.140Z - debug:  [17696] Using TFS proxy: 
2020-10-23T17:16:04.141Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T17:16:04.142Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T17:16:04.143Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T17:16:04.143Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T17:16:04.153Z - debug:  [17696] TFVC: spawned new process (duration: 9ms)
2020-10-23T17:16:05.132Z - debug:  [17696] TFVC: add exit code: 0 (duration: 2796ms)
2020-10-23T17:16:05.134Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-23T17:16:05.134Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-23T17:16:05.135Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-23T17:16:05.136Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-23T17:16:05.142Z - debug:  [17696] TFVC: spawned new process (duration: 5ms)
2020-10-23T17:16:05.436Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T17:16:05.437Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T17:16:05.437Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T17:16:05.440Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T17:16:05.440Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T17:16:05.441Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T17:16:05.441Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T17:16:05.446Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T17:16:05.446Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T17:16:05.447Z - debug:  [17696] Using TFS proxy: 
2020-10-23T17:16:05.447Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T17:16:05.448Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T17:16:05.448Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T17:16:05.449Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T17:16:05.454Z - debug:  [17696] TFVC: spawned new process (duration: 4ms)
2020-10-23T17:16:07.195Z - debug:  [17696] TFVC: add exit code: 0 (duration: 1745ms)
2020-10-23T17:16:07.195Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-23T17:16:07.196Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-23T17:16:07.196Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-23T17:16:07.196Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-23T17:16:07.202Z - debug:  [17696] TFVC: spawned new process (duration: 5ms)
2020-10-23T17:16:07.225Z - debug:  [17696] TFVC: add exit code: 0 (duration: 3081ms)
2020-10-23T17:16:07.226Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-23T17:16:07.226Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-23T17:16:07.226Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-23T17:16:07.227Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-23T17:16:07.234Z - debug:  [17696] TFVC: spawned new process (duration: 6ms)
2020-10-23T17:16:11.020Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 5883ms)
2020-10-23T17:16:11.023Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-23T17:16:11.024Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-23T17:16:11.025Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 3798ms)
2020-10-23T17:16:11.028Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-23T17:16:11.028Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-23T17:16:11.045Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 3849ms)
2020-10-23T17:16:11.046Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-23T17:16:11.046Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-23T17:16:18.672Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T17:16:18.674Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T17:16:18.675Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T17:16:18.679Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T17:16:18.679Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T17:16:18.680Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T17:16:18.680Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T17:16:18.701Z - debug:  [17696] Reinitializing due to onDidChangeConfiguration
2020-10-23T17:16:18.702Z - debug:  [17696] Polling interval value (minutes): 5
2020-10-23T17:16:18.702Z - debug:  [17696] Polling interval must be greater than 10 minutes.
2020-10-23T17:16:18.710Z - info:   [17696] *** FOLDER: y:\Test_Projects\Python ***
2020-10-23T17:16:18.711Z - info:   [17696] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-23T17:16:18.711Z - debug:  [17696] Looking for an External Context at y:\Test_Projects\Python
2020-10-23T17:16:18.711Z - debug:  [17696] No External Context at y:\Test_Projects\Python
2020-10-23T17:16:18.727Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T17:16:18.727Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T17:16:18.728Z - debug:  [17696] Using TFS proxy: 
2020-10-23T17:16:18.729Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T17:16:18.731Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T17:16:18.732Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T17:16:18.732Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T17:16:18.732Z - debug:  [17696] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-23T17:16:18.732Z - debug:  [17696] TFVC Creating Tfvc object with localPath='undefined'
2020-10-23T17:16:18.733Z - debug:  [17696] Using TFS proxy: 
2020-10-23T17:16:18.733Z - debug:  [17696] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-23T17:16:18.734Z - debug:  [17696] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-23T17:16:18.734Z - debug:  [17696] TFVC Repository.CheckVersion
2020-10-23T17:16:18.734Z - debug:  [17696] TFVC: tf add -noprompt -?
2020-10-23T17:16:18.852Z - debug:  [17696] TFVC: spawned new process (duration: 117ms)
2020-10-23T17:16:18.853Z - debug:  [17696] TFVC: spawned new process (duration: 80ms)
2020-10-23T17:16:18.853Z - error:  [17696] write after end
2020-10-23T17:16:19.045Z - debug:  [17696] TFVC: add exit code: 0 (duration: 313ms)
2020-10-23T17:16:19.046Z - debug:  [17696] TFVC Minimum required version: 14.102.0
2020-10-23T17:16:19.046Z - debug:  [17696] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-23T17:16:19.046Z - debug:  [17696] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-23T17:16:19.046Z - debug:  [17696] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-23T17:16:19.052Z - debug:  [17696] TFVC: spawned new process (duration: 5ms)
2020-10-23T17:16:19.792Z - debug:  [17696] TFVC: workfold exit code: 100 (duration: 746ms)
2020-10-23T17:16:19.794Z - debug:  [17696] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-23T17:16:19.795Z - error:  [17696] Execution of the TFVC command line failed unexpectedly.
2020-10-24T16:29:25.064Z - info:   [09896] *** FOLDER: y:\Test_Projects\Python ***
2020-10-24T16:29:25.065Z - info:   [09896] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-24T16:29:25.065Z - debug:  [09896] Looking for an External Context at y:\Test_Projects\Python
2020-10-24T16:29:25.065Z - debug:  [09896] No External Context at y:\Test_Projects\Python
2020-10-24T16:29:25.122Z - debug:  [09896] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-24T16:29:25.123Z - debug:  [09896] TFVC Creating Tfvc object with localPath='undefined'
2020-10-24T16:29:25.124Z - debug:  [09896] Using TFS proxy: 
2020-10-24T16:29:25.124Z - debug:  [09896] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-24T16:29:25.153Z - debug:  [09896] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-24T16:29:25.155Z - debug:  [09896] TFVC Repository.CheckVersion
2020-10-24T16:29:25.156Z - debug:  [09896] TFVC: tf add -noprompt -?
2020-10-24T16:29:25.333Z - debug:  [09896] TFVC: spawned new process (duration: 176ms)
2020-10-24T16:29:25.345Z - debug:  [09896] TFVC: spawned new process (duration: 10ms)
2020-10-24T16:29:32.597Z - debug:  [09896] TFVC: add exit code: 0 (duration: 7441ms)
2020-10-24T16:29:32.599Z - debug:  [09896] TFVC Minimum required version: 14.102.0
2020-10-24T16:29:32.600Z - debug:  [09896] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-24T16:29:32.600Z - debug:  [09896] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-24T16:29:32.601Z - debug:  [09896] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-24T16:29:32.612Z - debug:  [09896] TFVC: spawned new process (duration: 10ms)
2020-10-24T16:29:43.814Z - debug:  [09896] TFVC: workfold exit code: 100 (duration: 11213ms)
2020-10-24T16:29:43.817Z - debug:  [09896] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-24T16:29:43.821Z - error:  [09896] Execution of the TFVC command line failed unexpectedly.
2020-10-25T19:37:47.447Z - debug:  [09896] Reinitializing due to onDidChangeConfiguration
2020-10-25T19:37:47.452Z - debug:  [09896] Polling interval value (minutes): 5
2020-10-25T19:37:47.452Z - debug:  [09896] Polling interval must be greater than 10 minutes.
2020-10-25T19:37:47.463Z - info:   [09896] *** FOLDER: y:\Test_Projects\Python ***
2020-10-25T19:37:47.464Z - info:   [09896] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-25T19:37:47.465Z - debug:  [09896] Looking for an External Context at y:\Test_Projects\Python
2020-10-25T19:37:47.466Z - debug:  [09896] No External Context at y:\Test_Projects\Python
2020-10-25T19:37:47.486Z - debug:  [09896] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-25T19:37:47.487Z - debug:  [09896] TFVC Creating Tfvc object with localPath='undefined'
2020-10-25T19:37:47.488Z - debug:  [09896] Using TFS proxy: 
2020-10-25T19:37:47.489Z - debug:  [09896] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-25T19:37:47.490Z - debug:  [09896] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-25T19:37:47.491Z - debug:  [09896] TFVC Repository.CheckVersion
2020-10-25T19:37:47.494Z - debug:  [09896] TFVC: tf add -noprompt -?
2020-10-25T19:37:47.540Z - debug:  [09896] TFVC: spawned new process (duration: 44ms)
2020-10-25T19:37:48.279Z - debug:  [09896] TFVC: add exit code: 0 (duration: 784ms)
2020-10-25T19:37:48.282Z - debug:  [09896] TFVC Minimum required version: 14.102.0
2020-10-25T19:37:48.282Z - debug:  [09896] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-25T19:37:48.283Z - debug:  [09896] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-25T19:37:48.284Z - debug:  [09896] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-25T19:37:48.293Z - debug:  [09896] TFVC: spawned new process (duration: 7ms)
2020-10-25T19:37:51.450Z - debug:  [09896] TFVC: workfold exit code: 100 (duration: 3166ms)
2020-10-25T19:37:51.453Z - debug:  [09896] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-25T19:37:51.454Z - error:  [09896] Execution of the TFVC command line failed unexpectedly.
2020-10-31T17:00:28.239Z - info:   [16940] *** FOLDER: y:\Test_Projects\Python ***
2020-10-31T17:00:28.241Z - info:   [16940] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-10-31T17:00:28.242Z - debug:  [16940] Looking for an External Context at y:\Test_Projects\Python
2020-10-31T17:00:28.242Z - debug:  [16940] No External Context at y:\Test_Projects\Python
2020-10-31T17:00:28.253Z - debug:  [16940] Looking for TFVC repository at y:\Test_Projects\Python
2020-10-31T17:00:28.253Z - debug:  [16940] TFVC Creating Tfvc object with localPath='undefined'
2020-10-31T17:00:28.254Z - debug:  [16940] Using TFS proxy: 
2020-10-31T17:00:28.254Z - debug:  [16940] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-10-31T17:00:28.613Z - debug:  [16940] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-10-31T17:00:28.615Z - debug:  [16940] TFVC Repository.CheckVersion
2020-10-31T17:00:28.615Z - debug:  [16940] TFVC: tf add -noprompt -?
2020-10-31T17:00:29.307Z - debug:  [16940] TFVC: spawned new process (duration: 691ms)
2020-10-31T17:00:29.318Z - debug:  [16940] TFVC: spawned new process (duration: 9ms)
2020-10-31T17:01:03.965Z - debug:  [16940] TFVC: add exit code: 0 (duration: 35350ms)
2020-10-31T17:01:03.967Z - debug:  [16940] TFVC Minimum required version: 14.102.0
2020-10-31T17:01:03.967Z - debug:  [16940] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-10-31T17:01:03.968Z - debug:  [16940] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-10-31T17:01:03.968Z - debug:  [16940] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-10-31T17:01:03.980Z - debug:  [16940] TFVC: spawned new process (duration: 11ms)
2020-10-31T17:01:11.353Z - debug:  [16940] TFVC: workfold exit code: 100 (duration: 7384ms)
2020-10-31T17:01:11.355Z - debug:  [16940] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-10-31T17:01:11.357Z - error:  [16940] Execution of the TFVC command line failed unexpectedly.
2020-11-01T12:57:07.935Z - info:   [15648] *** FOLDER: y:\Test_Projects\Python ***
2020-11-01T12:57:07.935Z - info:   [15648] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-01T12:57:07.935Z - debug:  [15648] Looking for an External Context at y:\Test_Projects\Python
2020-11-01T12:57:07.935Z - debug:  [15648] No External Context at y:\Test_Projects\Python
2020-11-01T12:57:08.339Z - debug:  [15648] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-01T12:57:08.339Z - debug:  [15648] TFVC Creating Tfvc object with localPath='undefined'
2020-11-01T12:57:08.340Z - debug:  [15648] Using TFS proxy: 
2020-11-01T12:57:08.340Z - debug:  [15648] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-01T12:57:08.483Z - debug:  [15648] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-01T12:57:08.483Z - debug:  [15648] TFVC Repository.CheckVersion
2020-11-01T12:57:08.483Z - debug:  [15648] TFVC: tf add -noprompt -?
2020-11-01T12:57:08.704Z - debug:  [15648] TFVC: spawned new process (duration: 221ms)
2020-11-01T12:57:08.829Z - debug:  [15648] TFVC: spawned new process (duration: 109ms)
2020-11-01T12:57:33.355Z - debug:  [15648] TFVC: add exit code: 0 (duration: 24872ms)
2020-11-01T12:57:33.357Z - debug:  [15648] TFVC Minimum required version: 14.102.0
2020-11-01T12:57:33.357Z - debug:  [15648] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-01T12:57:33.358Z - debug:  [15648] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-01T12:57:33.358Z - debug:  [15648] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-01T12:57:33.369Z - debug:  [15648] TFVC: spawned new process (duration: 10ms)
2020-11-01T12:57:51.526Z - debug:  [15648] TFVC: workfold exit code: 100 (duration: 18168ms)
2020-11-01T12:57:51.529Z - debug:  [15648] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-01T12:57:51.529Z - error:  [15648] Execution of the TFVC command line failed unexpectedly.
2020-11-04T14:30:31.277Z - info:   [15908] *** FOLDER: y:\Test_Projects\Python ***
2020-11-04T14:30:31.279Z - info:   [15908] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-04T14:30:31.279Z - debug:  [15908] Looking for an External Context at y:\Test_Projects\Python
2020-11-04T14:30:31.279Z - debug:  [15908] No External Context at y:\Test_Projects\Python
2020-11-04T14:30:31.287Z - debug:  [15908] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-04T14:30:31.288Z - debug:  [15908] TFVC Creating Tfvc object with localPath='undefined'
2020-11-04T14:30:31.289Z - debug:  [15908] Using TFS proxy: 
2020-11-04T14:30:31.289Z - debug:  [15908] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-04T14:30:31.642Z - debug:  [15908] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-04T14:30:31.643Z - debug:  [15908] TFVC Repository.CheckVersion
2020-11-04T14:30:31.644Z - debug:  [15908] TFVC: tf add -noprompt -?
2020-11-04T14:30:31.809Z - debug:  [15908] TFVC: spawned new process (duration: 163ms)
2020-11-04T14:30:31.820Z - debug:  [15908] TFVC: spawned new process (duration: 9ms)
2020-11-04T14:30:46.179Z - debug:  [15908] TFVC: add exit code: 0 (duration: 14534ms)
2020-11-04T14:30:46.180Z - debug:  [15908] TFVC Minimum required version: 14.102.0
2020-11-04T14:30:46.180Z - debug:  [15908] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-04T14:30:46.180Z - debug:  [15908] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-04T14:30:46.181Z - debug:  [15908] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-04T14:30:46.191Z - debug:  [15908] TFVC: spawned new process (duration: 8ms)
2020-11-04T14:30:54.218Z - debug:  [15908] TFVC: workfold exit code: 100 (duration: 8037ms)
2020-11-04T14:30:54.220Z - debug:  [15908] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-04T14:30:54.221Z - error:  [15908] Execution of the TFVC command line failed unexpectedly.
2020-11-05T17:02:34.984Z - info:   [0384] *** FOLDER: y:\Test_Projects\Python ***
2020-11-05T17:02:34.986Z - info:   [0384] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-05T17:02:34.987Z - debug:  [0384] Looking for an External Context at y:\Test_Projects\Python
2020-11-05T17:02:34.987Z - debug:  [0384] No External Context at y:\Test_Projects\Python
2020-11-05T17:02:35.023Z - debug:  [0384] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-05T17:02:35.023Z - debug:  [0384] TFVC Creating Tfvc object with localPath='undefined'
2020-11-05T17:02:35.024Z - debug:  [0384] Using TFS proxy: 
2020-11-05T17:02:35.024Z - debug:  [0384] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-05T17:02:35.356Z - debug:  [0384] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-05T17:02:35.358Z - debug:  [0384] TFVC Repository.CheckVersion
2020-11-05T17:02:35.359Z - debug:  [0384] TFVC: tf add -noprompt -?
2020-11-05T17:02:35.619Z - debug:  [0384] TFVC: spawned new process (duration: 259ms)
2020-11-05T17:02:35.630Z - debug:  [0384] TFVC: spawned new process (duration: 10ms)
2020-11-05T17:02:47.976Z - debug:  [0384] TFVC: add exit code: 0 (duration: 12617ms)
2020-11-05T17:02:47.978Z - debug:  [0384] TFVC Minimum required version: 14.102.0
2020-11-05T17:02:47.978Z - debug:  [0384] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-05T17:02:47.979Z - debug:  [0384] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-05T17:02:47.980Z - debug:  [0384] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-05T17:02:47.995Z - debug:  [0384] TFVC: spawned new process (duration: 14ms)
2020-11-05T17:03:11.874Z - debug:  [0384] TFVC: workfold exit code: 100 (duration: 23894ms)
2020-11-05T17:03:11.903Z - debug:  [0384] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-05T17:03:11.904Z - error:  [0384] Execution of the TFVC command line failed unexpectedly.
2020-11-05T17:37:03.851Z - info:   [19096] *** FOLDER: y:\Test_Projects\Python ***
2020-11-05T17:37:03.853Z - info:   [19096] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-05T17:37:03.853Z - debug:  [19096] Looking for an External Context at y:\Test_Projects\Python
2020-11-05T17:37:03.854Z - debug:  [19096] No External Context at y:\Test_Projects\Python
2020-11-05T17:37:03.864Z - debug:  [19096] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-05T17:37:03.864Z - debug:  [19096] TFVC Creating Tfvc object with localPath='undefined'
2020-11-05T17:37:03.865Z - debug:  [19096] Using TFS proxy: 
2020-11-05T17:37:03.865Z - debug:  [19096] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-05T17:37:03.866Z - debug:  [19096] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-05T17:37:03.867Z - debug:  [19096] TFVC Repository.CheckVersion
2020-11-05T17:37:03.868Z - debug:  [19096] TFVC: tf add -noprompt -?
2020-11-05T17:37:03.878Z - debug:  [19096] TFVC: spawned new process (duration: 9ms)
2020-11-05T17:37:03.887Z - debug:  [19096] TFVC: spawned new process (duration: 8ms)
2020-11-05T17:37:07.333Z - debug:  [19096] TFVC: add exit code: 0 (duration: 3464ms)
2020-11-05T17:37:07.335Z - debug:  [19096] TFVC Minimum required version: 14.102.0
2020-11-05T17:37:07.335Z - debug:  [19096] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-05T17:37:07.336Z - debug:  [19096] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-05T17:37:07.336Z - debug:  [19096] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-05T17:37:07.350Z - debug:  [19096] TFVC: spawned new process (duration: 13ms)
2020-11-05T17:37:08.979Z - debug:  [19096] TFVC: workfold exit code: 100 (duration: 1642ms)
2020-11-05T17:37:08.981Z - debug:  [19096] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-05T17:37:08.983Z - error:  [19096] Execution of the TFVC command line failed unexpectedly.
2020-11-05T17:46:26.828Z - debug:  [19096] Reinitializing due to onDidChangeConfiguration
2020-11-05T17:46:26.831Z - debug:  [19096] Polling interval value (minutes): 5
2020-11-05T17:46:26.831Z - debug:  [19096] Polling interval must be greater than 10 minutes.
2020-11-05T17:46:26.841Z - info:   [19096] *** FOLDER: y:\Test_Projects\Python ***
2020-11-05T17:46:26.841Z - info:   [19096] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-05T17:46:26.842Z - debug:  [19096] Looking for an External Context at y:\Test_Projects\Python
2020-11-05T17:46:26.843Z - debug:  [19096] No External Context at y:\Test_Projects\Python
2020-11-05T17:46:26.858Z - debug:  [19096] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-05T17:46:26.858Z - debug:  [19096] TFVC Creating Tfvc object with localPath='undefined'
2020-11-05T17:46:26.859Z - debug:  [19096] Using TFS proxy: 
2020-11-05T17:46:26.859Z - debug:  [19096] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-05T17:46:26.860Z - debug:  [19096] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-05T17:46:26.861Z - debug:  [19096] TFVC Repository.CheckVersion
2020-11-05T17:46:26.862Z - debug:  [19096] TFVC: tf add -noprompt -?
2020-11-05T17:46:26.872Z - debug:  [19096] TFVC: spawned new process (duration: 9ms)
2020-11-05T17:46:27.042Z - debug:  [19096] TFVC: add exit code: 0 (duration: 180ms)
2020-11-05T17:46:27.043Z - debug:  [19096] TFVC Minimum required version: 14.102.0
2020-11-05T17:46:27.043Z - debug:  [19096] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-05T17:46:27.044Z - debug:  [19096] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-05T17:46:27.044Z - debug:  [19096] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-05T17:46:27.054Z - debug:  [19096] TFVC: spawned new process (duration: 9ms)
2020-11-05T17:46:28.494Z - debug:  [19096] TFVC: workfold exit code: 100 (duration: 1450ms)
2020-11-05T17:46:28.495Z - debug:  [19096] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-05T17:46:28.496Z - error:  [19096] Execution of the TFVC command line failed unexpectedly.
2020-11-06T04:30:40.987Z - info:   [01876] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T04:30:40.989Z - info:   [01876] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T04:30:40.989Z - debug:  [01876] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T04:30:40.989Z - debug:  [01876] No External Context at y:\Test_Projects\Python
2020-11-06T04:30:40.999Z - debug:  [01876] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T04:30:40.999Z - debug:  [01876] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T04:30:40.999Z - debug:  [01876] Using TFS proxy: 
2020-11-06T04:30:40.999Z - debug:  [01876] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T04:30:40.999Z - debug:  [01876] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T04:30:40.999Z - debug:  [01876] TFVC Repository.CheckVersion
2020-11-06T04:30:40.999Z - debug:  [01876] TFVC: tf add -noprompt -?
2020-11-06T04:30:41.128Z - debug:  [01876] TFVC: spawned new process (duration: 122ms)
2020-11-06T04:30:41.149Z - debug:  [01876] TFVC: spawned new process (duration: 21ms)
2020-11-06T04:30:45.743Z - debug:  [01876] TFVC: add exit code: 0 (duration: 4744ms)
2020-11-06T04:30:45.745Z - debug:  [01876] TFVC Minimum required version: 14.102.0
2020-11-06T04:30:45.745Z - debug:  [01876] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T04:30:45.746Z - debug:  [01876] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T04:30:45.748Z - debug:  [01876] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T04:30:45.758Z - debug:  [01876] TFVC: spawned new process (duration: 9ms)
2020-11-06T04:30:47.473Z - debug:  [01876] TFVC: workfold exit code: 100 (duration: 1725ms)
2020-11-06T04:30:47.475Z - debug:  [01876] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T04:30:47.476Z - error:  [01876] Execution of the TFVC command line failed unexpectedly.
2020-11-06T04:37:01.903Z - debug:  [01876] Reinitializing due to onDidChangeConfiguration
2020-11-06T04:37:01.906Z - debug:  [01876] Polling interval value (minutes): 5
2020-11-06T04:37:01.906Z - debug:  [01876] Polling interval must be greater than 10 minutes.
2020-11-06T04:37:01.914Z - info:   [01876] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T04:37:01.914Z - info:   [01876] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T04:37:01.915Z - debug:  [01876] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T04:37:01.916Z - debug:  [01876] No External Context at y:\Test_Projects\Python
2020-11-06T04:37:01.930Z - debug:  [01876] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T04:37:01.931Z - debug:  [01876] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T04:37:01.934Z - debug:  [01876] Using TFS proxy: 
2020-11-06T04:37:01.934Z - debug:  [01876] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T04:37:01.936Z - debug:  [01876] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T04:37:01.937Z - debug:  [01876] TFVC Repository.CheckVersion
2020-11-06T04:37:01.939Z - debug:  [01876] TFVC: tf add -noprompt -?
2020-11-06T04:37:01.951Z - debug:  [01876] TFVC: spawned new process (duration: 10ms)
2020-11-06T04:37:02.140Z - debug:  [01876] TFVC: add exit code: 0 (duration: 199ms)
2020-11-06T04:37:02.141Z - debug:  [01876] TFVC Minimum required version: 14.102.0
2020-11-06T04:37:02.142Z - debug:  [01876] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T04:37:02.142Z - debug:  [01876] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T04:37:02.143Z - debug:  [01876] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T04:37:02.152Z - debug:  [01876] TFVC: spawned new process (duration: 8ms)
2020-11-06T04:37:03.497Z - debug:  [01876] TFVC: workfold exit code: 100 (duration: 1354ms)
2020-11-06T04:37:03.500Z - debug:  [01876] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T04:37:03.501Z - error:  [01876] Execution of the TFVC command line failed unexpectedly.
2020-11-06T04:59:13.746Z - info:   [23504] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T04:59:13.748Z - info:   [23504] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T04:59:13.749Z - debug:  [23504] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T04:59:13.749Z - debug:  [23504] No External Context at y:\Test_Projects\Python
2020-11-06T04:59:13.760Z - debug:  [23504] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T04:59:13.760Z - debug:  [23504] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T04:59:13.761Z - debug:  [23504] Using TFS proxy: 
2020-11-06T04:59:13.761Z - debug:  [23504] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T04:59:13.762Z - debug:  [23504] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T04:59:13.764Z - debug:  [23504] TFVC Repository.CheckVersion
2020-11-06T04:59:13.765Z - debug:  [23504] TFVC: tf add -noprompt -?
2020-11-06T04:59:13.782Z - debug:  [23504] TFVC: spawned new process (duration: 16ms)
2020-11-06T04:59:13.793Z - debug:  [23504] TFVC: spawned new process (duration: 9ms)
2020-11-06T04:59:16.051Z - debug:  [23504] TFVC: add exit code: 0 (duration: 2286ms)
2020-11-06T04:59:16.053Z - debug:  [23504] TFVC Minimum required version: 14.102.0
2020-11-06T04:59:16.053Z - debug:  [23504] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T04:59:16.054Z - debug:  [23504] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T04:59:16.054Z - debug:  [23504] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T04:59:16.065Z - debug:  [23504] TFVC: spawned new process (duration: 10ms)
2020-11-06T04:59:17.519Z - debug:  [23504] TFVC: workfold exit code: 100 (duration: 1464ms)
2020-11-06T04:59:17.521Z - debug:  [23504] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T04:59:17.523Z - error:  [23504] Execution of the TFVC command line failed unexpectedly.
2020-11-06T05:25:17.132Z - info:   [11160] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T05:25:17.147Z - info:   [11160] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T05:25:17.147Z - debug:  [11160] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T05:25:17.147Z - debug:  [11160] No External Context at y:\Test_Projects\Python
2020-11-06T05:25:17.366Z - debug:  [11160] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T05:25:17.366Z - debug:  [11160] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T05:25:17.366Z - debug:  [11160] Using TFS proxy: 
2020-11-06T05:25:17.366Z - debug:  [11160] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T05:25:17.608Z - debug:  [11160] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T05:25:17.608Z - debug:  [11160] TFVC Repository.CheckVersion
2020-11-06T05:25:17.608Z - debug:  [11160] TFVC: tf add -noprompt -?
2020-11-06T05:25:17.850Z - debug:  [11160] TFVC: spawned new process (duration: 227ms)
2020-11-06T05:25:17.865Z - debug:  [11160] TFVC: spawned new process (duration: 14ms)
2020-11-06T05:26:01.650Z - debug:  [11160] TFVC: add exit code: 0 (duration: 44042ms)
2020-11-06T05:26:01.651Z - debug:  [11160] TFVC Minimum required version: 14.102.0
2020-11-06T05:26:01.652Z - debug:  [11160] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T05:26:01.652Z - debug:  [11160] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T05:26:01.654Z - debug:  [11160] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T05:26:01.663Z - debug:  [11160] TFVC: spawned new process (duration: 8ms)
2020-11-06T05:26:17.361Z - debug:  [11160] TFVC: workfold exit code: 100 (duration: 15707ms)
2020-11-06T05:26:17.363Z - debug:  [11160] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T05:26:17.364Z - error:  [11160] Execution of the TFVC command line failed unexpectedly.
2020-11-06T05:34:30.109Z - info:   [18264] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T05:34:30.111Z - info:   [18264] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T05:34:30.111Z - debug:  [18264] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T05:34:30.112Z - debug:  [18264] No External Context at y:\Test_Projects\Python
2020-11-06T05:34:30.126Z - debug:  [18264] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T05:34:30.126Z - debug:  [18264] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T05:34:30.131Z - debug:  [18264] Using TFS proxy: 
2020-11-06T05:34:30.131Z - debug:  [18264] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T05:34:30.132Z - debug:  [18264] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T05:34:30.134Z - debug:  [18264] TFVC Repository.CheckVersion
2020-11-06T05:34:30.135Z - debug:  [18264] TFVC: tf add -noprompt -?
2020-11-06T05:34:30.147Z - debug:  [18264] TFVC: spawned new process (duration: 11ms)
2020-11-06T05:34:30.180Z - debug:  [18264] TFVC: spawned new process (duration: 32ms)
2020-11-06T05:34:32.207Z - debug:  [18264] TFVC: add exit code: 0 (duration: 2072ms)
2020-11-06T05:34:32.210Z - debug:  [18264] TFVC Minimum required version: 14.102.0
2020-11-06T05:34:32.210Z - debug:  [18264] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T05:34:32.211Z - debug:  [18264] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T05:34:32.211Z - debug:  [18264] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T05:34:32.218Z - debug:  [18264] TFVC: spawned new process (duration: 6ms)
2020-11-06T05:34:33.940Z - debug:  [18264] TFVC: workfold exit code: 100 (duration: 1729ms)
2020-11-06T05:34:33.942Z - debug:  [18264] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T05:34:33.943Z - error:  [18264] Execution of the TFVC command line failed unexpectedly.
2020-11-06T05:36:01.258Z - debug:  [18264] Reinitializing due to onDidChangeConfiguration
2020-11-06T05:36:01.261Z - debug:  [18264] Polling interval value (minutes): 5
2020-11-06T05:36:01.261Z - debug:  [18264] Polling interval must be greater than 10 minutes.
2020-11-06T05:36:01.267Z - info:   [18264] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T05:36:01.267Z - info:   [18264] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T05:36:01.268Z - debug:  [18264] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T05:36:01.268Z - debug:  [18264] No External Context at y:\Test_Projects\Python
2020-11-06T05:36:01.282Z - debug:  [18264] Reinitializing due to onDidChangeConfiguration
2020-11-06T05:36:01.287Z - debug:  [18264] Polling interval value (minutes): 5
2020-11-06T05:36:01.287Z - debug:  [18264] Polling interval must be greater than 10 minutes.
2020-11-06T05:36:01.290Z - info:   [18264] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T05:36:01.290Z - info:   [18264] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T05:36:01.291Z - debug:  [18264] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T05:36:01.291Z - debug:  [18264] No External Context at y:\Test_Projects\Python
2020-11-06T05:36:01.305Z - debug:  [18264] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T05:36:01.305Z - debug:  [18264] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T05:36:01.306Z - debug:  [18264] Using TFS proxy: 
2020-11-06T05:36:01.306Z - debug:  [18264] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T05:36:01.307Z - debug:  [18264] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T05:36:01.308Z - debug:  [18264] TFVC Repository.CheckVersion
2020-11-06T05:36:01.309Z - debug:  [18264] TFVC: tf add -noprompt -?
2020-11-06T05:36:01.310Z - debug:  [18264] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T05:36:01.310Z - debug:  [18264] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T05:36:01.310Z - debug:  [18264] Using TFS proxy: 
2020-11-06T05:36:01.310Z - debug:  [18264] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T05:36:01.311Z - debug:  [18264] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T05:36:01.312Z - debug:  [18264] TFVC Repository.CheckVersion
2020-11-06T05:36:01.312Z - debug:  [18264] TFVC: tf add -noprompt -?
2020-11-06T05:36:01.339Z - debug:  [18264] TFVC: spawned new process (duration: 26ms)
2020-11-06T05:36:01.339Z - debug:  [18264] TFVC: spawned new process (duration: 15ms)
2020-11-06T05:36:01.339Z - error:  [18264] write after end
2020-11-06T05:36:01.497Z - debug:  [18264] TFVC: add exit code: 0 (duration: 188ms)
2020-11-06T05:36:01.499Z - debug:  [18264] TFVC Minimum required version: 14.102.0
2020-11-06T05:36:01.499Z - debug:  [18264] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T05:36:01.500Z - debug:  [18264] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T05:36:01.500Z - debug:  [18264] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T05:36:01.509Z - debug:  [18264] TFVC: spawned new process (duration: 8ms)
2020-11-06T05:36:02.001Z - debug:  [18264] Reinitializing due to onDidChangeConfiguration
2020-11-06T05:36:02.002Z - debug:  [18264] Polling interval value (minutes): 5
2020-11-06T05:36:02.002Z - debug:  [18264] Polling interval must be greater than 10 minutes.
2020-11-06T05:36:02.005Z - info:   [18264] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T05:36:02.006Z - info:   [18264] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T05:36:02.006Z - debug:  [18264] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T05:36:02.006Z - debug:  [18264] No External Context at y:\Test_Projects\Python
2020-11-06T05:36:02.010Z - debug:  [18264] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T05:36:02.011Z - debug:  [18264] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T05:36:02.011Z - debug:  [18264] Using TFS proxy: 
2020-11-06T05:36:02.011Z - debug:  [18264] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T05:36:02.012Z - debug:  [18264] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T05:36:02.012Z - debug:  [18264] TFVC Repository.CheckVersion
2020-11-06T05:36:02.013Z - debug:  [18264] TFVC: tf add -noprompt -?
2020-11-06T05:36:02.019Z - debug:  [18264] TFVC: spawned new process (duration: 6ms)
2020-11-06T05:36:02.752Z - debug:  [18264] TFVC: add exit code: 0 (duration: 739ms)
2020-11-06T05:36:02.753Z - debug:  [18264] TFVC Minimum required version: 14.102.0
2020-11-06T05:36:02.753Z - debug:  [18264] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T05:36:02.753Z - debug:  [18264] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T05:36:02.753Z - debug:  [18264] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T05:36:02.762Z - debug:  [18264] TFVC: spawned new process (duration: 8ms)
2020-11-06T05:36:02.995Z - debug:  [18264] TFVC: workfold exit code: 100 (duration: 1495ms)
2020-11-06T05:36:02.998Z - debug:  [18264] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T05:36:02.998Z - error:  [18264] Execution of the TFVC command line failed unexpectedly.
2020-11-06T05:36:03.097Z - debug:  [18264] TFVC: workfold exit code: 100 (duration: 344ms)
2020-11-06T05:36:03.103Z - debug:  [18264] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T05:36:03.104Z - error:  [18264] Execution of the TFVC command line failed unexpectedly.
2020-11-06T06:03:57.185Z - info:   [14056] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T06:03:57.187Z - info:   [14056] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T06:03:57.187Z - debug:  [14056] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T06:03:57.187Z - debug:  [14056] No External Context at y:\Test_Projects\Python
2020-11-06T06:03:57.196Z - debug:  [14056] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T06:03:57.196Z - debug:  [14056] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T06:03:57.197Z - debug:  [14056] Using TFS proxy: 
2020-11-06T06:03:57.197Z - debug:  [14056] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T06:03:57.198Z - debug:  [14056] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T06:03:57.198Z - debug:  [14056] TFVC Repository.CheckVersion
2020-11-06T06:03:57.199Z - debug:  [14056] TFVC: tf add -noprompt -?
2020-11-06T06:03:57.208Z - debug:  [14056] TFVC: spawned new process (duration: 8ms)
2020-11-06T06:03:57.219Z - debug:  [14056] TFVC: spawned new process (duration: 10ms)
2020-11-06T06:03:58.600Z - debug:  [14056] TFVC: add exit code: 0 (duration: 1401ms)
2020-11-06T06:03:58.602Z - debug:  [14056] TFVC Minimum required version: 14.102.0
2020-11-06T06:03:58.602Z - debug:  [14056] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T06:03:58.603Z - debug:  [14056] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T06:03:58.603Z - debug:  [14056] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T06:03:58.614Z - debug:  [14056] TFVC: spawned new process (duration: 10ms)
2020-11-06T06:03:59.192Z - debug:  [14056] TFVC: workfold exit code: 100 (duration: 589ms)
2020-11-06T06:03:59.194Z - debug:  [14056] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T06:03:59.195Z - error:  [14056] Execution of the TFVC command line failed unexpectedly.
2020-11-06T06:22:48.369Z - debug:  [14056] Reinitializing due to onDidChangeConfiguration
2020-11-06T06:22:48.373Z - debug:  [14056] Polling interval value (minutes): 5
2020-11-06T06:22:48.373Z - debug:  [14056] Polling interval must be greater than 10 minutes.
2020-11-06T06:22:48.381Z - info:   [14056] *** FOLDER: y:\Test_Projects\Python ***
2020-11-06T06:22:48.381Z - info:   [14056] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-06T06:22:48.383Z - debug:  [14056] Looking for an External Context at y:\Test_Projects\Python
2020-11-06T06:22:48.383Z - debug:  [14056] No External Context at y:\Test_Projects\Python
2020-11-06T06:22:48.400Z - debug:  [14056] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-06T06:22:48.400Z - debug:  [14056] TFVC Creating Tfvc object with localPath='undefined'
2020-11-06T06:22:48.404Z - debug:  [14056] Using TFS proxy: 
2020-11-06T06:22:48.404Z - debug:  [14056] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-06T06:22:48.405Z - debug:  [14056] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-06T06:22:48.406Z - debug:  [14056] TFVC Repository.CheckVersion
2020-11-06T06:22:48.407Z - debug:  [14056] TFVC: tf add -noprompt -?
2020-11-06T06:22:48.420Z - debug:  [14056] TFVC: spawned new process (duration: 11ms)
2020-11-06T06:22:48.769Z - debug:  [14056] TFVC: add exit code: 0 (duration: 360ms)
2020-11-06T06:22:48.770Z - debug:  [14056] TFVC Minimum required version: 14.102.0
2020-11-06T06:22:48.771Z - debug:  [14056] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-06T06:22:48.771Z - debug:  [14056] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-06T06:22:48.772Z - debug:  [14056] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-06T06:22:48.781Z - debug:  [14056] TFVC: spawned new process (duration: 8ms)
2020-11-06T06:22:49.233Z - debug:  [14056] TFVC: workfold exit code: 100 (duration: 461ms)
2020-11-06T06:22:49.235Z - debug:  [14056] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-06T06:22:49.236Z - error:  [14056] Execution of the TFVC command line failed unexpectedly.
2020-11-07T06:07:22.286Z - debug:  [14056] Reinitializing due to onDidChangeConfiguration
2020-11-07T06:07:22.290Z - debug:  [14056] Polling interval value (minutes): 5
2020-11-07T06:07:22.290Z - debug:  [14056] Polling interval must be greater than 10 minutes.
2020-11-07T06:07:22.300Z - info:   [14056] *** FOLDER: y:\Test_Projects\Python ***
2020-11-07T06:07:22.301Z - info:   [14056] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-07T06:07:22.302Z - debug:  [14056] Looking for an External Context at y:\Test_Projects\Python
2020-11-07T06:07:22.302Z - debug:  [14056] No External Context at y:\Test_Projects\Python
2020-11-07T06:07:22.322Z - debug:  [14056] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-07T06:07:22.323Z - debug:  [14056] TFVC Creating Tfvc object with localPath='undefined'
2020-11-07T06:07:22.324Z - debug:  [14056] Using TFS proxy: 
2020-11-07T06:07:22.324Z - debug:  [14056] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-07T06:07:22.325Z - debug:  [14056] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-07T06:07:22.326Z - debug:  [14056] TFVC Repository.CheckVersion
2020-11-07T06:07:22.327Z - debug:  [14056] TFVC: tf add -noprompt -?
2020-11-07T06:07:22.536Z - debug:  [14056] TFVC: spawned new process (duration: 208ms)
2020-11-07T06:07:23.354Z - debug:  [14056] TFVC: add exit code: 0 (duration: 1027ms)
2020-11-07T06:07:23.357Z - debug:  [14056] TFVC Minimum required version: 14.102.0
2020-11-07T06:07:23.357Z - debug:  [14056] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-07T06:07:23.358Z - debug:  [14056] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-07T06:07:23.358Z - debug:  [14056] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-07T06:07:23.367Z - debug:  [14056] TFVC: spawned new process (duration: 8ms)
2020-11-07T06:07:26.302Z - debug:  [14056] TFVC: workfold exit code: 100 (duration: 2944ms)
2020-11-07T06:07:26.305Z - debug:  [14056] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-07T06:07:26.306Z - error:  [14056] Execution of the TFVC command line failed unexpectedly.
2020-11-08T15:47:31.741Z - debug:  [14056] Reinitializing due to onDidChangeConfiguration
2020-11-08T15:47:31.744Z - debug:  [14056] Polling interval value (minutes): 5
2020-11-08T15:47:31.744Z - debug:  [14056] Polling interval must be greater than 10 minutes.
2020-11-08T15:47:31.747Z - info:   [14056] *** FOLDER: y:\Test_Projects\Python ***
2020-11-08T15:47:31.748Z - info:   [14056] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-08T15:47:31.748Z - debug:  [14056] Looking for an External Context at y:\Test_Projects\Python
2020-11-08T15:47:31.749Z - debug:  [14056] No External Context at y:\Test_Projects\Python
2020-11-08T15:47:31.758Z - debug:  [14056] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-08T15:47:31.758Z - debug:  [14056] TFVC Creating Tfvc object with localPath='undefined'
2020-11-08T15:47:31.759Z - debug:  [14056] Using TFS proxy: 
2020-11-08T15:47:31.759Z - debug:  [14056] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-08T15:47:31.759Z - debug:  [14056] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-08T15:47:31.760Z - debug:  [14056] TFVC Repository.CheckVersion
2020-11-08T15:47:31.761Z - debug:  [14056] TFVC: tf add -noprompt -?
2020-11-08T15:47:31.777Z - debug:  [14056] TFVC: spawned new process (duration: 16ms)
2020-11-08T15:47:32.679Z - debug:  [14056] TFVC: add exit code: 0 (duration: 918ms)
2020-11-08T15:47:32.680Z - debug:  [14056] TFVC Minimum required version: 14.102.0
2020-11-08T15:47:32.680Z - debug:  [14056] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-08T15:47:32.681Z - debug:  [14056] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-08T15:47:32.681Z - debug:  [14056] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-08T15:47:32.687Z - debug:  [14056] TFVC: spawned new process (duration: 5ms)
2020-11-08T15:47:36.069Z - debug:  [14056] TFVC: workfold exit code: 100 (duration: 3387ms)
2020-11-08T15:47:36.070Z - debug:  [14056] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-08T15:47:36.071Z - error:  [14056] Execution of the TFVC command line failed unexpectedly.
2020-11-08T15:51:17.272Z - info:   [22520] *** FOLDER: y:\Test_Projects\Python ***
2020-11-08T15:51:17.274Z - info:   [22520] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-08T15:51:17.274Z - debug:  [22520] Looking for an External Context at y:\Test_Projects\Python
2020-11-08T15:51:17.275Z - debug:  [22520] No External Context at y:\Test_Projects\Python
2020-11-08T15:51:17.287Z - debug:  [22520] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-08T15:51:17.287Z - debug:  [22520] TFVC Creating Tfvc object with localPath='undefined'
2020-11-08T15:51:17.288Z - debug:  [22520] Using TFS proxy: 
2020-11-08T15:51:17.289Z - debug:  [22520] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-08T15:51:17.290Z - debug:  [22520] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-08T15:51:17.291Z - debug:  [22520] TFVC Repository.CheckVersion
2020-11-08T15:51:17.292Z - debug:  [22520] TFVC: tf add -noprompt -?
2020-11-08T15:51:17.300Z - debug:  [22520] TFVC: spawned new process (duration: 6ms)
2020-11-08T15:51:17.306Z - debug:  [22520] TFVC: spawned new process (duration: 5ms)
2020-11-08T15:51:25.195Z - debug:  [22520] TFVC: add exit code: 0 (duration: 7901ms)
2020-11-08T15:51:25.197Z - debug:  [22520] TFVC Minimum required version: 14.102.0
2020-11-08T15:51:25.198Z - debug:  [22520] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-08T15:51:25.199Z - debug:  [22520] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-08T15:51:25.200Z - debug:  [22520] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-08T15:51:25.211Z - debug:  [22520] TFVC: spawned new process (duration: 6ms)
2020-11-08T15:51:26.490Z - debug:  [22520] TFVC: workfold exit code: 100 (duration: 1289ms)
2020-11-08T15:51:26.492Z - debug:  [22520] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-08T15:51:26.494Z - error:  [22520] Execution of the TFVC command line failed unexpectedly.
2020-11-12T13:28:03.489Z - info:   [09744] *** FOLDER: y:\Test_Projects\Python ***
2020-11-12T13:28:03.491Z - info:   [09744] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-12T13:28:03.491Z - debug:  [09744] Looking for an External Context at y:\Test_Projects\Python
2020-11-12T13:28:03.491Z - debug:  [09744] No External Context at y:\Test_Projects\Python
2020-11-12T13:28:03.515Z - debug:  [09744] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-12T13:28:03.515Z - debug:  [09744] TFVC Creating Tfvc object with localPath='undefined'
2020-11-12T13:28:03.517Z - debug:  [09744] Using TFS proxy: 
2020-11-12T13:28:03.517Z - debug:  [09744] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-12T13:28:03.595Z - debug:  [09744] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-12T13:28:03.597Z - debug:  [09744] TFVC Repository.CheckVersion
2020-11-12T13:28:03.598Z - debug:  [09744] TFVC: tf add -noprompt -?
2020-11-12T13:28:03.699Z - debug:  [09744] TFVC: spawned new process (duration: 101ms)
2020-11-12T13:28:03.707Z - debug:  [09744] TFVC: spawned new process (duration: 6ms)
2020-11-12T13:28:37.890Z - debug:  [09744] TFVC: add exit code: 0 (duration: 34282ms)
2020-11-12T13:28:37.894Z - debug:  [09744] TFVC Minimum required version: 14.102.0
2020-11-12T13:28:37.894Z - debug:  [09744] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-12T13:28:37.895Z - debug:  [09744] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-12T13:28:37.896Z - debug:  [09744] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-12T13:28:37.904Z - debug:  [09744] TFVC: spawned new process (duration: 6ms)
2020-11-12T13:28:46.746Z - debug:  [09744] TFVC: workfold exit code: 100 (duration: 8849ms)
2020-11-12T13:28:46.747Z - debug:  [09744] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-12T13:28:46.749Z - error:  [09744] Execution of the TFVC command line failed unexpectedly.
2020-11-12T13:30:00.614Z - debug:  [09744] Reinitializing due to onDidChangeConfiguration
2020-11-12T13:30:00.617Z - debug:  [09744] Polling interval value (minutes): 5
2020-11-12T13:30:00.618Z - debug:  [09744] Polling interval must be greater than 10 minutes.
2020-11-12T13:30:00.630Z - info:   [09744] *** FOLDER: y:\Test_Projects\Python ***
2020-11-12T13:30:00.630Z - info:   [09744] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-12T13:30:00.632Z - debug:  [09744] Looking for an External Context at y:\Test_Projects\Python
2020-11-12T13:30:00.632Z - debug:  [09744] No External Context at y:\Test_Projects\Python
2020-11-12T13:30:00.647Z - debug:  [09744] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-12T13:30:00.647Z - debug:  [09744] TFVC Creating Tfvc object with localPath='undefined'
2020-11-12T13:30:00.649Z - debug:  [09744] Using TFS proxy: 
2020-11-12T13:30:00.649Z - debug:  [09744] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-12T13:30:00.650Z - debug:  [09744] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-12T13:30:00.652Z - debug:  [09744] TFVC Repository.CheckVersion
2020-11-12T13:30:00.652Z - debug:  [09744] TFVC: tf add -noprompt -?
2020-11-12T13:30:00.660Z - debug:  [09744] TFVC: spawned new process (duration: 6ms)
2020-11-12T13:30:01.580Z - debug:  [09744] TFVC: add exit code: 0 (duration: 928ms)
2020-11-12T13:30:01.582Z - debug:  [09744] TFVC Minimum required version: 14.102.0
2020-11-12T13:30:01.582Z - debug:  [09744] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-12T13:30:01.583Z - debug:  [09744] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-12T13:30:01.583Z - debug:  [09744] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-12T13:30:01.590Z - debug:  [09744] TFVC: spawned new process (duration: 5ms)
2020-11-12T13:30:03.473Z - debug:  [09744] TFVC: workfold exit code: 100 (duration: 1889ms)
2020-11-12T13:30:03.475Z - debug:  [09744] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-12T13:30:03.476Z - error:  [09744] Execution of the TFVC command line failed unexpectedly.
2020-11-12T13:30:04.002Z - debug:  [09744] Reinitializing due to onDidChangeConfiguration
2020-11-12T13:30:04.004Z - debug:  [09744] Polling interval value (minutes): 5
2020-11-12T13:30:04.004Z - debug:  [09744] Polling interval must be greater than 10 minutes.
2020-11-12T13:30:04.007Z - info:   [09744] *** FOLDER: y:\Test_Projects\Python ***
2020-11-12T13:30:04.008Z - info:   [09744] AzureReposVSCode/1.161.1 (VSCode 1.50.1; Windows_NT 10.0.17134; Node 12.14.1)
2020-11-12T13:30:04.008Z - debug:  [09744] Looking for an External Context at y:\Test_Projects\Python
2020-11-12T13:30:04.009Z - debug:  [09744] No External Context at y:\Test_Projects\Python
2020-11-12T13:30:04.019Z - debug:  [09744] Looking for TFVC repository at y:\Test_Projects\Python
2020-11-12T13:30:04.020Z - debug:  [09744] TFVC Creating Tfvc object with localPath='undefined'
2020-11-12T13:30:04.021Z - debug:  [09744] Using TFS proxy: 
2020-11-12T13:30:04.021Z - debug:  [09744] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2020-11-12T13:30:04.021Z - debug:  [09744] TFVC Repository created with repositoryRootFolder='y:\Test_Projects\Python'
2020-11-12T13:30:04.023Z - debug:  [09744] TFVC Repository.CheckVersion
2020-11-12T13:30:04.023Z - debug:  [09744] TFVC: tf add -noprompt -?
2020-11-12T13:30:04.030Z - debug:  [09744] TFVC: spawned new process (duration: 6ms)
2020-11-12T13:30:04.178Z - debug:  [09744] TFVC: add exit code: 0 (duration: 154ms)
2020-11-12T13:30:04.179Z - debug:  [09744] TFVC Minimum required version: 14.102.0
2020-11-12T13:30:04.179Z - debug:  [09744] TFVC (TF.exe, TF.cmd) version: 15.123.27127.4
2020-11-12T13:30:04.180Z - debug:  [09744] TFVC Repository.FindWorkspace with localPath='y:\Test_Projects\Python'
2020-11-12T13:30:04.180Z - debug:  [09744] TFVC: tf workfold -noprompt y:\Test_Projects\Python
2020-11-12T13:30:04.186Z - debug:  [09744] TFVC: spawned new process (duration: 5ms)
2020-11-12T13:30:04.918Z - debug:  [09744] TFVC: workfold exit code: 100 (duration: 738ms)
2020-11-12T13:30:04.920Z - debug:  [09744] TFVC errors (via stderr): Unable to determine the workspace. You may be able to correct this by running 'tf workspaces /collection:TeamProjectCollectionUrl'.

2020-11-12T13:30:04.921Z - error:  [09744] Execution of the TFVC command line failed unexpectedly.
